// Generated by GitHub Copilot
// Keep the provider stable during dev; avoid using the hot-swap API here so the build can compile cleanly.

import {
  createContext,
  useContext,
  useEffect,
  useState,
  type ReactNode,
} from "react";
import { storage } from "../storage/IndexedDBStorage";
import type { StorageService } from "../storage/StorageService";
import type { Settings } from "../types";

interface StorageContextValue {
  storage: StorageService;
  settings: Settings;
  refreshSettings: () => Promise<void>;
}

const StorageContext = createContext<StorageContextValue | null>(null);

function applyTheme(theme: Settings["theme"]) {
  const isDark =
    theme === "dark" ||
    (theme === "system" &&
      window.matchMedia("(prefers-color-scheme: dark)").matches);
  document.documentElement.classList.toggle("dark", isDark);
}

// Generated by GitHub Copilot
export function StorageProvider({ children }: { children: ReactNode }) {
  const [settings, setSettings] = useState<Settings | null>(null);
  const [error, setError] = useState<string | null>(null);

  const refreshSettings = async () => {
    const s = await storage.getSettings();
    setSettings(s);
    applyTheme(s.theme);
  };

  useEffect(() => {
    storage
      .initialize()
      .then(refreshSettings)
      .catch((err) => setError(String(err)));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Keep the dark class in sync when the OS preference changes
  useEffect(() => {
    if (settings?.theme !== "system") return;
    const mq = window.matchMedia("(prefers-color-scheme: dark)");
    const handler = () => applyTheme("system");
    mq.addEventListener("change", handler);
    return () => mq.removeEventListener("change", handler);
  }, [settings?.theme]);

  if (error) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-red-50 p-8 text-center">
        <div>
          <p className="font-semibold text-red-600 mb-1">
            Failed to open database
          </p>
          <p className="text-sm text-slate-600">{error}</p>
          <p className="text-xs text-slate-500 mt-3">
            Private / incognito mode may block IndexedDB access.
          </p>
        </div>
      </div>
    );
  }

  if (!settings) {
    return (
      <div
        className="flex items-center justify-center min-h-screen bg-slate-50"
        aria-label="Loading application"
        role="status"
      >
        <div className="w-10 h-10 rounded-full border-2 border-indigo-500 border-t-transparent animate-spin" />
      </div>
    );
  }

  return (
    <StorageContext.Provider value={{ storage, settings, refreshSettings }}>
      {children}
    </StorageContext.Provider>
  );
}

export function useStorageContext(): StorageContextValue {
  const ctx = useContext(StorageContext);
  if (!ctx)
    throw new Error("useStorageContext must be used inside <StorageProvider>");
  return ctx;
}
