// Generated by GitHub Copilot
import { useState, useEffect, useCallback } from 'react'
import { useStorage } from './useStorage'
import type { Account } from '../types'

export function useAccounts() {
  const { storage } = useStorage()
  const [accounts, setAccounts] = useState<Account[]>([])
  const [loading, setLoading] = useState(true)

  const reload = useCallback(async () => {
    const data = await storage.getAccounts()
    setAccounts(data)
    setLoading(false)
  }, [storage])

  useEffect(() => {
    reload()
  }, [reload])

  return { accounts, loading, reload }
}
