// Generated by GitHub Copilot
import { useState, useEffect, useCallback } from 'react'
import { useStorage } from './useStorage'
import { getCurrentMonth } from '../utils/date'
import type { Budget } from '../types'

export function useBudgets(month?: string) {
  const { storage } = useStorage()
  const targetMonth = month ?? getCurrentMonth()
  const [budgets, setBudgets] = useState<Budget[]>([])
  const [loading, setLoading] = useState(true)

  const reload = useCallback(async () => {
    const data = await storage.getBudgets(targetMonth)
    setBudgets(data)
    setLoading(false)
  }, [storage, targetMonth])

  useEffect(() => {
    reload()
  }, [reload])

  return { budgets, loading, reload }
}
