// Generated by GitHub Copilot
import { useState, useEffect } from 'react'
import { useStorage } from './useStorage'
import type { Category } from '../types'

export function useCategories() {
  const { storage } = useStorage()
  const [categories, setCategories] = useState<Category[]>([])

  useEffect(() => {
    storage.getCategories().then(setCategories)
  }, [storage])

  return categories
}
