// Generated by GitHub Copilot
import { useState, useEffect, useCallback } from 'react'
import { useStorage } from './useStorage'
import type { ParentBudget, BudgetAllocation } from '../types'

export function useParentBudgets() {
  const { storage } = useStorage()
  const [parentBudgets, setParentBudgets] = useState<ParentBudget[]>([])
  const [allocations, setAllocations] = useState<BudgetAllocation[]>([])
  const [loading, setLoading] = useState(true)

  const reload = useCallback(async () => {
    const [budgets, allocs] = await Promise.all([
      storage.getParentBudgets(),
      storage.getBudgetAllocations(),
    ])
    setParentBudgets(budgets)
    setAllocations(allocs)
    setLoading(false)
  }, [storage])

  useEffect(() => {
    reload()
  }, [reload])

  return { parentBudgets, allocations, loading, reload }
}
