// Generated by GitHub Copilot
import { useStorageContext } from '../contexts/StorageContext'

/** Access the storage service, current settings, and a settings refresh callback. */
export function useStorage() {
  return useStorageContext()
}
