// Generated by GitHub Copilot
import { useState, useEffect, useCallback } from 'react'
import { useStorage } from './useStorage'
import type { Transaction } from '../types'

export function useTransactions() {
  const { storage } = useStorage()
  const [transactions, setTransactions] = useState<Transaction[]>([])
  const [loading, setLoading] = useState(true)

  const reload = useCallback(async () => {
    const data = await storage.getTransactions()
    setTransactions(data)
    setLoading(false)
  }, [storage])

  useEffect(() => {
    reload()
  }, [reload])

  return { transactions, loading, reload }
}
