// Generated by GitHub Copilot
import { NavLink } from 'react-router-dom'
import { HomeIcon, TransactionsIcon, BudgetsIcon, ReportsIcon, SettingsIcon } from '../icons/NavIcons'

const NAV_ITEMS = [
  { to: '/',             label: 'Dashboard',    Icon: HomeIcon,         end: true  },
  { to: '/transactions', label: 'Transactions', Icon: TransactionsIcon, end: false },
  { to: '/budgets',      label: 'Budgets',      Icon: BudgetsIcon,      end: false },
  { to: '/reports',      label: 'Reports',      Icon: ReportsIcon,      end: false },
  { to: '/settings',     label: 'Settings',     Icon: SettingsIcon,     end: false },
]

/** Mobile-only bottom tab bar. Hidden on lg+ screens. */
export default function BottomNav() {
  return (
    <nav
      aria-label="Main navigation"
      className="lg:hidden flex items-stretch border-t border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900"
    >
      {NAV_ITEMS.map(({ to, label, Icon, end }) => (
        <NavLink
          key={to}
          to={to}
          end={end}
          className={({ isActive }) =>
            `flex flex-col items-center justify-center gap-1 flex-1 py-3 min-h-[56px] transition-colors ${
              isActive
                ? 'text-indigo-600 dark:text-indigo-400'
                : 'text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-300'
            }`
          }
        >
          {({ isActive }) => (
            <>
              <Icon size={22} />
              <span
                className={`text-[10px] leading-none ${isActive ? 'font-semibold' : 'font-medium'}`}
              >
                {label}
              </span>
            </>
          )}
        </NavLink>
      ))}
    </nav>
  )
}
