// Generated by GitHub Copilot
import { Outlet } from 'react-router-dom'
import BottomNav from './BottomNav'
import Sidebar from './Sidebar'

/** Root layout — sidebar on desktop, bottom nav on mobile. */
export default function Layout() {
  return (
    <div className="flex h-dvh bg-slate-50 dark:bg-slate-950 overflow-hidden">
      <Sidebar />

      <div className="flex flex-col flex-1 min-w-0 overflow-hidden">
        <main className="flex-1 overflow-y-auto" id="main-content">
          {/* pb-24 leaves space for the bottom nav on mobile */}
          <div className="max-w-2xl mx-auto px-4 py-5 pb-24 lg:pb-6 lg:py-6 lg:px-8">
            <Outlet />
          </div>
        </main>

        <BottomNav />
      </div>
    </div>
  )
}
