// Generated by GitHub Copilot
import { NavLink } from 'react-router-dom'
import { HomeIcon, TransactionsIcon, BudgetsIcon, ReportsIcon, SettingsIcon } from '../icons/NavIcons'

const NAV_ITEMS = [
  { to: '/',             label: 'Dashboard',    Icon: HomeIcon,         end: true  },
  { to: '/transactions', label: 'Transactions', Icon: TransactionsIcon, end: false },
  { to: '/budgets',      label: 'Budgets',      Icon: BudgetsIcon,      end: false },
  { to: '/reports',      label: 'Reports',      Icon: ReportsIcon,      end: false },
  { to: '/settings',     label: 'Settings',     Icon: SettingsIcon,     end: false },
]

/** Desktop sidebar navigation. Hidden on screens smaller than lg. */
export default function Sidebar() {
  return (
    <aside
      aria-label="Sidebar navigation"
      className="hidden lg:flex flex-col w-64 shrink-0 bg-white dark:bg-slate-900 border-r border-slate-200 dark:border-slate-800"
    >
      {/* Branding */}
      <div className="flex items-center gap-3 px-6 h-16 border-b border-slate-200 dark:border-slate-800">
        <div className="w-8 h-8 rounded-lg bg-indigo-600 flex items-center justify-center shrink-0" aria-hidden="true">
          <span className="text-white text-sm font-bold">₹</span>
        </div>
        <h1 className="text-lg font-bold text-slate-900 dark:text-white leading-tight">
          Budget Tracker
        </h1>
      </div>

      {/* Nav links */}
      <nav aria-label="Main navigation" className="flex-1 px-3 py-4 space-y-0.5 overflow-y-auto">
        {NAV_ITEMS.map(({ to, label, Icon, end }) => (
          <NavLink
            key={to}
            to={to}
            end={end}
            className={({ isActive }) =>
              `flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-medium transition-colors ${
                isActive
                  ? 'bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300'
                  : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 hover:text-slate-900 dark:hover:text-slate-100'
              }`
            }
          >
            {({ isActive }) => (
              <>
                <Icon size={20} />
                <span>{label}</span>
                {isActive && <span className="ml-auto w-1.5 h-1.5 rounded-full bg-indigo-600 dark:bg-indigo-400" aria-hidden="true" />}
              </>
            )}
          </NavLink>
        ))}
      </nav>

      <div className="px-6 py-4 border-t border-slate-200 dark:border-slate-800">
        <p className="text-xs text-slate-400 dark:text-slate-600">v1.0 · All data stored locally</p>
      </div>
    </aside>
  )
}
