// Generated by GitHub Copilot
export type TransactionType = 'income' | 'expense' | 'transfer'
export type ThemeMode = 'light' | 'dark' | 'system'
export type AccountType = 'savings' | 'credit_card'

/** A single financial transaction. */
export interface Transaction {
  id: string
  type: TransactionType
  /** Always positive; direction is determined by `type`. */
  amount: number
  /** YYYY-MM-DD */
  date: string
  categoryId?: string
  accountId?: string
  toAccountId?: string
  notes?: string
  merchant?: string
  paymentMethod?: string
  tags?: string[]
  createdAt: string
  updatedAt: string
}

/** Income or expense category. */
export interface Category {
  id: string
  name: string
  type: 'income' | 'expense'
  icon?: string
  color?: string
  isDefault: boolean
  createdAt: string
}

/** Monthly spending limit for a category. */
export interface Budget {
  id: string
  categoryId: string
  amount: number
  /** YYYY-MM */
  month: string
  createdAt: string
  updatedAt: string
}

/** Bank account, savings account, or credit card. */
export interface Account {
  id: string
  name: string
  type: AccountType
  balance: number
  color: string
  createdAt: string
  updatedAt: string
}

/** Singleton settings row — always id = 1. */
export interface Settings {
  id: 1
  currency: string
  currencySymbol: string
  locale: string
  theme: ThemeMode
}

/** Singleton app metadata row — always id = 1. */
export interface AppMetadata {
  id: 1
  schemaVersion: number
  createdAt: string
  lastExportAt?: string
}

/** Shape of the full JSON export file. */
export interface ExportData {
  metadata: AppMetadata
  transactions: Transaction[]
  categories: Category[]
  budgets: Budget[]
  accounts: Account[]
  settings: Settings
  exportedAt: string
}
