// Generated by GitHub Copilot
import { useState, useMemo } from "react";
import { useBudgets } from "../hooks/useBudgets";
import { useTransactions } from "../hooks/useTransactions";
import { useCategories } from "../hooks/useCategories";
import { useStorage } from "../hooks/useStorage";
import BottomSheet from "../components/ui/BottomSheet";
import BudgetForm from "../features/budgets/BudgetForm";
import BudgetProgress from "../features/budgets/BudgetProgress";
import { PlusIcon } from "../components/icons/NavIcons";
import { formatCurrency } from "../utils/currency";
import { formatMonthYear, getCurrentMonth, addMonths } from "../utils/date";
import type { Budget } from "../types";

export default function BudgetsPage() {
  const { settings } = useStorage();
  const [month, setMonth] = useState(getCurrentMonth());
  const { budgets, loading, reload } = useBudgets(month);
  const { transactions } = useTransactions();
  const categories = useCategories();
  const [sheetOpen, setSheetOpen] = useState(false);
  const [editTarget, setEditTarget] = useState<Budget | undefined>();

  const spending = useMemo(() => {
    const map = new Map<string, number>();
    for (const tx of transactions) {
      if (!tx.categoryId) continue;
      if (tx.date.startsWith(month) && tx.type === "expense")
        map.set(tx.categoryId, (map.get(tx.categoryId) ?? 0) + tx.amount);
    }
    return map;
  }, [transactions, month]);

  const catMap = useMemo(
    () => new Map(categories.map((c) => [c.id, c])),
    [categories],
  );

  const totals = useMemo(() => {
    const totalBudget = budgets.reduce((s, b) => s + b.amount, 0);
    const totalSpent = budgets.reduce(
      (s, b) => s + (spending.get(b.categoryId) ?? 0),
      0,
    );
    return { totalBudget, totalSpent, remaining: totalBudget - totalSpent };
  }, [budgets, spending]);

  const fmt = (n: number) =>
    formatCurrency(n, settings.currencySymbol, settings.locale);
  function openAdd() {
    setEditTarget(undefined);
    setSheetOpen(true);
  }
  function openEdit(b: Budget) {
    setEditTarget(b);
    setSheetOpen(true);
  }
  function handleSuccess() {
    setSheetOpen(false);
    reload();
  }

  return (
    <>
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white">
            Budgets
          </h1>
          <button
            type="button"
            onClick={openAdd}
            className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 text-white px-4 py-2.5 rounded-xl text-sm font-semibold transition-colors min-h-[44px]"
          >
            <PlusIcon size={18} />
            Add
          </button>
        </div>

        {/* Month selector */}
        <div className="flex items-center justify-between bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl px-4 py-3">
          <button
            type="button"
            onClick={() => setMonth((m) => addMonths(m, -1))}
            aria-label="Previous month"
            className="w-9 h-9 flex items-center justify-center rounded-xl text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
          >
            <svg
              width={20}
              height={20}
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth={2}
              strokeLinecap="round"
              aria-hidden="true"
            >
              <path d="M15 18l-6-6 6-6" />
            </svg>
          </button>
          <span className="text-sm font-semibold text-slate-900 dark:text-white">
            {formatMonthYear(month)}
          </span>
          <button
            type="button"
            onClick={() => setMonth((m) => addMonths(m, 1))}
            aria-label="Next month"
            className="w-9 h-9 flex items-center justify-center rounded-xl text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
          >
            <svg
              width={20}
              height={20}
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth={2}
              strokeLinecap="round"
              aria-hidden="true"
            >
              <path d="M9 18l6-6-6-6" />
            </svg>
          </button>
        </div>

        {/* Totals summary — only shown when budgets exist */}
        {!loading && budgets.length > 0 && (
          <div className="grid grid-cols-3 gap-3">
            <TotalPill label="Budget" value={fmt(totals.totalBudget)} />
            <TotalPill
              label="Spent"
              value={fmt(totals.totalSpent)}
              red={totals.totalSpent > totals.totalBudget}
            />
            <TotalPill
              label="Remaining"
              value={fmt(Math.abs(totals.remaining))}
              green={totals.remaining >= 0}
              red={totals.remaining < 0}
            />
          </div>
        )}

        {loading ? (
          <div
            className="flex justify-center py-12"
            role="status"
            aria-label="Loading budgets"
          >
            <div className="w-8 h-8 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin" />
          </div>
        ) : budgets.length === 0 ? (
          <div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-8 text-center">
            <span className="text-4xl" aria-hidden="true">
              🎯
            </span>
            <p className="mt-3 font-semibold text-slate-700 dark:text-slate-300">
              No budgets for this month
            </p>
            <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
              Tap <strong>Add</strong> to set a spending limit per category.
            </p>
          </div>
        ) : (
          <div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden">
            <div className="divide-y divide-slate-100 dark:divide-slate-800">
              {budgets.map((b) => (
                <BudgetProgress
                  key={b.id}
                  budget={b}
                  category={catMap.get(b.categoryId)}
                  spent={spending.get(b.categoryId) ?? 0}
                  currencySymbol={settings.currencySymbol}
                  locale={settings.locale}
                  onClick={() => openEdit(b)}
                />
              ))}
            </div>
          </div>
        )}
      </div>

      <BottomSheet
        open={sheetOpen}
        onClose={() => setSheetOpen(false)}
        title={editTarget ? "Edit Budget" : "Set Budget"}
      >
        {sheetOpen && (
          <BudgetForm
            budget={editTarget}
            month={month}
            existingBudgets={budgets}
            categories={categories}
            onSuccess={handleSuccess}
          />
        )}
      </BottomSheet>
    </>
  );
}

function TotalPill({
  label,
  value,
  green,
  red,
}: {
  label: string;
  value: string;
  green?: boolean;
  red?: boolean;
}) {
  const color = red
    ? "text-rose-600 dark:text-rose-400"
    : green
      ? "text-emerald-600 dark:text-emerald-400"
      : "text-slate-900 dark:text-white";
  return (
    <div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 px-3 py-3 text-center">
      <p className="text-xs font-medium text-slate-500 dark:text-slate-400 mb-1">
        {label}
      </p>
      <p className={`text-sm font-bold leading-tight ${color}`}>{value}</p>
    </div>
  );
}
