// Generated by GitHub Copilot
import { useState, useMemo } from "react";
import { useParentBudgets } from "../hooks/useParentBudgets";
import { useTransactions } from "../hooks/useTransactions";
import { useCategories } from "../hooks/useCategories";
import { useStorage } from "../hooks/useStorage";
import BottomSheet from "../components/ui/BottomSheet";
import BudgetForm from "../features/budgets/BudgetForm";
import BudgetAllocationForm from "../features/budgets/BudgetAllocationForm";
import BudgetProgress from "../features/budgets/BudgetProgress";
import { PlusIcon } from "../components/icons/NavIcons";
import { formatCurrency } from "../utils/currency";
import { formatMonthYear, formatDate } from "../utils/date";
import type { ParentBudget, BudgetAllocation } from "../types";

/** Returns a human-readable period label for a budget. */
function budgetPeriodLabel(b: ParentBudget): string {
  const type = b.budgetType ?? 'custom'
  if (type === 'monthly' && b.month) return formatMonthYear(b.month)
  if (b.startDate && b.endDate)
    return `${formatDate(b.startDate)} – ${formatDate(b.endDate)}`
  return 'No period set'
}

export default function BudgetsPage() {
  const { settings } = useStorage();
  const { parentBudgets, allocations, loading, reload } = useParentBudgets();
  const { transactions } = useTransactions();
  const { categories } = useCategories();

  // Accordion — which parent budget rows are expanded
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set());

  // Sheet: create/edit parent budget
  const [budgetSheet, setBudgetSheet] = useState(false);
  const [editBudget, setEditBudget] = useState<ParentBudget | undefined>();

  // Sheet: add/edit allocation
  const [allocSheet, setAllocSheet] = useState(false);
  const [allocBudgetId, setAllocBudgetId] = useState<string>("");
  const [editAlloc, setEditAlloc] = useState<BudgetAllocation | undefined>();

  const catMap = useMemo(
    () => new Map(categories.map((c) => [c.id, c])),
    [categories],
  );

  /** spending[budgetId][categoryId] = total spent */
  const spending = useMemo(() => {
    const map = new Map<string, Map<string, number>>();
    for (const tx of transactions) {
      if (!tx.budgetId || tx.type !== "expense") continue;
      if (!map.has(tx.budgetId)) map.set(tx.budgetId, new Map());
      const catSpend = map.get(tx.budgetId)!;
      const catId = tx.categoryId ?? "";
      catSpend.set(catId, (catSpend.get(catId) ?? 0) + tx.amount);
    }
    return map;
  }, [transactions]);

  const budgetTotalSpent = (budgetId: string) => {
    const catMap = spending.get(budgetId);
    if (!catMap) return 0;
    return Array.from(catMap.values()).reduce((s, v) => s + v, 0);
  };

  const fmt = (n: number) =>
    formatCurrency(n, settings.currencySymbol, settings.locale);

  function toggleExpand(id: string) {
    setExpandedIds((prev) => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  }

  function openAddBudget() {
    setEditBudget(undefined);
    setBudgetSheet(true);
  }

  function openEditBudget(b: ParentBudget) {
    setEditBudget(b);
    setBudgetSheet(true);
  }

  function openAddAlloc(budgetId: string) {
    setAllocBudgetId(budgetId);
    setEditAlloc(undefined);
    setAllocSheet(true);
  }

  function openEditAlloc(alloc: BudgetAllocation) {
    setAllocBudgetId(alloc.budgetId);
    setEditAlloc(alloc);
    setAllocSheet(true);
  }

  function handleBudgetSuccess() {
    setBudgetSheet(false);
    reload();
  }

  function handleAllocSuccess() {
    setAllocSheet(false);
    reload();
  }

  const allocationsForBudget = (budgetId: string) =>
    allocations.filter((a) => a.budgetId === budgetId);

  return (
    <>
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white">
            Budgets
          </h1>
          <button
            type="button"
            onClick={openAddBudget}
            className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 text-white px-4 py-2.5 rounded-xl text-sm font-semibold transition-colors min-h-[44px]"
          >
            <PlusIcon size={18} />
            New Budget
          </button>
        </div>

        {loading ? (
          <div
            className="flex justify-center py-12"
            role="status"
            aria-label="Loading budgets"
          >
            <div className="w-8 h-8 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin" />
          </div>
        ) : parentBudgets.length === 0 ? (
          <div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-8 text-center">
            <span className="text-4xl" aria-hidden="true">🎯</span>
            <p className="mt-3 font-semibold text-slate-700 dark:text-slate-300">
              No budgets yet
            </p>
            <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
              Tap <strong>New Budget</strong> to create a spending plan.
            </p>
          </div>
        ) : (
          <div className="space-y-3">
            {parentBudgets.map((budget) => {
              const budgetAllocs = allocationsForBudget(budget.id);
              const totalAllocated = budgetAllocs.reduce((s, a) => s + a.amount, 0);
              const totalSpent = budgetTotalSpent(budget.id);
              const isExpanded = expandedIds.has(budget.id);
              const pct = budget.totalAmount > 0
                ? Math.min((totalSpent / budget.totalAmount) * 100, 100)
                : 0;
              const over = totalSpent > budget.totalAmount;
              const warn = !over && pct >= 80;
              const overAllocated = totalAllocated > budget.totalAmount;

              return (
                <div
                  key={budget.id}
                  className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden"
                >
                  {/* Parent budget header row */}
                  <div className="px-5 py-4">
                    <div className="flex items-start justify-between gap-3 mb-3">
                      <div className="min-w-0">
                        <div className="flex items-center gap-2 flex-wrap">
                          <h2 className="text-base font-bold text-slate-900 dark:text-white leading-tight">
                            {budget.name}
                          </h2>
                          <span className={`text-[10px] font-semibold px-1.5 py-0.5 rounded-full ${
                            (budget.budgetType ?? 'custom') === 'monthly'
                              ? 'bg-indigo-50 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400'
                              : 'bg-violet-50 dark:bg-violet-900/30 text-violet-600 dark:text-violet-400'
                          }`}>
                            {budgetPeriodLabel(budget)}
                          </span>
                          {over && (
                            <span className="text-[10px] font-bold text-rose-600 dark:text-rose-400 bg-rose-50 dark:bg-rose-900/30 px-1.5 py-0.5 rounded-full">
                              OVER
                            </span>
                          )}
                          {overAllocated && !over && (
                            <span className="text-[10px] font-bold text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-900/30 px-1.5 py-0.5 rounded-full">
                              OVER-ALLOCATED
                            </span>
                          )}
                        </div>
                        {budget.description && (
                          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5 truncate">
                            {budget.description}
                          </p>
                        )}
                      </div>
                      <div className="flex items-center gap-2 shrink-0">
                        <button
                          type="button"
                          onClick={() => openEditBudget(budget)}
                          aria-label={`Edit ${budget.name}`}
                          className="w-8 h-8 flex items-center justify-center rounded-lg text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
                        >
                          <svg width={16} height={16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                            <path d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7" />
                            <path d="M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z" />
                          </svg>
                        </button>
                        <button
                          type="button"
                          onClick={() => toggleExpand(budget.id)}
                          aria-expanded={isExpanded}
                          aria-label={isExpanded ? "Collapse" : "Expand"}
                          className="w-8 h-8 flex items-center justify-center rounded-lg text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
                        >
                          <svg
                            width={16}
                            height={16}
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth={2.5}
                            strokeLinecap="round"
                            aria-hidden="true"
                            className={`transition-transform duration-200 ${isExpanded ? 'rotate-180' : ''}`}
                          >
                            <path d="M6 9l6 6 6-6" />
                          </svg>
                        </button>
                      </div>
                    </div>

                    {/* Overall progress bar */}
                    <div className="space-y-1.5">
                      <div className="flex items-center justify-between text-xs">
                        <span className="text-slate-500 dark:text-slate-400">
                          {fmt(totalSpent)} spent
                        </span>
                        <span className={`font-semibold ${over ? 'text-rose-600 dark:text-rose-400' : warn ? 'text-amber-600 dark:text-amber-400' : 'text-slate-700 dark:text-slate-300'}`}>
                          {fmt(budget.totalAmount)} total
                        </span>
                      </div>
                      <div className="h-2.5 bg-slate-100 dark:bg-slate-700 rounded-full overflow-hidden">
                        <div
                          className={`h-full rounded-full transition-all duration-300 ${over ? 'bg-rose-500' : warn ? 'bg-amber-500' : 'bg-emerald-500'}`}
                          style={{ width: `${pct}%` }}
                          role="progressbar"
                          aria-valuenow={Math.round(pct)}
                          aria-valuemin={0}
                          aria-valuemax={100}
                          aria-label={`${Math.round(pct)}% of ${budget.name} budget used`}
                        />
                      </div>
                      <div className="flex items-center justify-between text-xs text-slate-400 dark:text-slate-500">
                        <span>{budgetAllocs.length} categor{budgetAllocs.length === 1 ? 'y' : 'ies'} · {fmt(totalAllocated)} allocated</span>
                        <span>{fmt(Math.max(0, budget.totalAmount - totalSpent))} remaining</span>
                      </div>
                    </div>
                  </div>

                  {/* Expanded: allocation rows + add button */}
                  {isExpanded && (
                    <div className="border-t border-slate-100 dark:border-slate-800">
                      {budgetAllocs.length > 0 && (
                        <div className="divide-y divide-slate-100 dark:divide-slate-800">
                          {budgetAllocs.map((alloc) => (
                            <BudgetProgress
                              key={alloc.id}
                              allocation={alloc}
                              category={catMap.get(alloc.categoryId)}
                              spent={spending.get(budget.id)?.get(alloc.categoryId) ?? 0}
                              currencySymbol={settings.currencySymbol}
                              locale={settings.locale}
                              onClick={() => openEditAlloc(alloc)}
                            />
                          ))}
                        </div>
                      )}
                      <div className="px-5 py-3">
                        <button
                          type="button"
                          onClick={() => openAddAlloc(budget.id)}
                          className="flex items-center gap-2 text-sm font-medium text-indigo-600 dark:text-indigo-400 hover:text-indigo-700 dark:hover:text-indigo-300 transition-colors"
                        >
                          <PlusIcon size={16} />
                          Add Category
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Parent budget form sheet */}
      <BottomSheet
        open={budgetSheet}
        onClose={() => setBudgetSheet(false)}
        title={editBudget ? "Edit Budget" : "New Budget"}
      >
        {budgetSheet && (
          <BudgetForm
            budget={editBudget}
            onSuccess={handleBudgetSuccess}
          />
        )}
      </BottomSheet>

      {/* Allocation form sheet */}
      <BottomSheet
        open={allocSheet}
        onClose={() => setAllocSheet(false)}
        title={editAlloc ? "Edit Category" : "Add Category"}
      >
        {allocSheet && (
          <BudgetAllocationForm
            budgetId={allocBudgetId}
            allocation={editAlloc}
            existingAllocations={allocations.filter(a => a.budgetId === allocBudgetId)}
            categories={categories}
            onSuccess={handleAllocSuccess}
          />
        )}
      </BottomSheet>
    </>
  );
}

