// Generated by GitHub Copilot
import { useMemo, useState } from 'react'
import { useStorage } from '../hooks/useStorage'
import { useTransactions } from '../hooks/useTransactions'
import { useCategories } from '../hooks/useCategories'
import { useAccounts } from '../hooks/useAccounts'
import { useBudgets } from '../hooks/useBudgets'
import { formatCurrency } from '../utils/currency'
import { formatMonthYear, getCurrentMonth, addMonths } from '../utils/date'
import BudgetProgress from '../features/budgets/BudgetProgress'
import type { Transaction, Account } from '../types'

export default function DashboardPage() {
  const { settings } = useStorage()
  const { transactions, loading } = useTransactions()
  const categories = useCategories()
  const { accounts } = useAccounts()
  const [month, setMonth] = useState(getCurrentMonth())
  const { budgets } = useBudgets(month)
  const catMap = useMemo(() => new Map(categories.map(c => [c.id, c])), [categories])

  const { income, expense, recent, spending } = useMemo(() => {
    const monthTxs = transactions.filter(tx => tx.date.startsWith(month))
    const spendMap = new Map<string, number>()
    for (const tx of monthTxs) {
      if (tx.type === 'expense') spendMap.set(tx.categoryId, (spendMap.get(tx.categoryId) ?? 0) + tx.amount)
    }
    return {
      income:   monthTxs.filter(tx => tx.type === 'income').reduce((s, tx) => s + tx.amount, 0),
      expense:  monthTxs.filter(tx => tx.type === 'expense').reduce((s, tx) => s + tx.amount, 0),
      recent:   transactions.filter(tx => tx.date.startsWith(month)).slice(0, 10),
      spending: spendMap,
    }
  }, [transactions, month])

  const balance = income - expense
  const fmt = (n: number) => formatCurrency(n, settings.currencySymbol, settings.locale)

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Overview</h1>
      </div>

      {/* Month selector */}
      <div className="flex items-center justify-between bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl px-4 py-3">
        <button
          type="button"
          onClick={() => setMonth(m => addMonths(m, -1))}
          aria-label="Previous month"
          className="w-9 h-9 flex items-center justify-center rounded-xl text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
        >
          <svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" aria-hidden="true"><path d="M15 18l-6-6 6-6"/></svg>
        </button>
        <span className="text-sm font-semibold text-slate-900 dark:text-white">{formatMonthYear(month)}</span>
        <button
          type="button"
          onClick={() => setMonth(m => addMonths(m, 1))}
          aria-label="Next month"
          className="w-9 h-9 flex items-center justify-center rounded-xl text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
        >
          <svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" aria-hidden="true"><path d="M9 18l6-6-6-6"/></svg>
        </button>
      </div>

      {/* Account balance cards */}
      {accounts.length > 0 && (
        <section aria-labelledby="accounts-heading">
          <h2 id="accounts-heading" className="text-base font-semibold text-slate-900 dark:text-white mb-3">Accounts</h2>
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
            {accounts.map(acc => <AccountBalanceCard key={acc.id} account={acc} fmt={fmt} />)}
          </div>
        </section>
      )}

      {/* Summary cards */}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
        <SummaryCard label="Income"   value={fmt(income)}           color="emerald" />
        <SummaryCard label="Expenses" value={fmt(expense)}          color="rose" />
        <div className="col-span-2 sm:col-span-1">
          <SummaryCard label="Balance" value={fmt(Math.abs(balance))} color={balance >= 0 ? 'indigo' : 'rose'} />
        </div>
      </div>

      {/* Budget overview */}
      {budgets.length > 0 && (
        <section aria-labelledby="budgets-dash-heading">
          <h2 id="budgets-dash-heading" className="text-base font-semibold text-slate-900 dark:text-white mb-3">Budgets</h2>
          <div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden">
            <div className="divide-y divide-slate-100 dark:divide-slate-800">
              {budgets.map(b => (
                <BudgetProgress
                  key={b.id}
                  budget={b}
                  category={catMap.get(b.categoryId)}
                  spent={spending.get(b.categoryId) ?? 0}
                  currencySymbol={settings.currencySymbol}
                  locale={settings.locale}
                  onClick={() => {}}
                />
              ))}
            </div>
          </div>
        </section>
      )}

      {/* Recent transactions */}
      <section aria-labelledby="recent-heading">
        <h2 id="recent-heading" className="text-base font-semibold text-slate-900 dark:text-white mb-3">
          Recent
        </h2>
        {loading ? (
          <div className="flex justify-center py-8" role="status" aria-label="Loading">
            <div className="w-7 h-7 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin" />
          </div>
        ) : recent.length === 0 ? (
          <div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 text-center">
            <span className="text-3xl" aria-hidden="true">💸</span>
            <p className="mt-2 text-sm font-semibold text-slate-700 dark:text-slate-300">No transactions yet</p>
          </div>
        ) : (
          <div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden">
            <div className="divide-y divide-slate-100 dark:divide-slate-800">
              {recent.map(tx => <RecentRow key={tx.id} tx={tx} catMap={catMap} fmt={fmt} />)}
            </div>
          </div>
        )}
      </section>
    </div>
  )
}

function AccountBalanceCard({ account, fmt }: { account: Account; fmt: (n: number) => string }) {
  const isCredit = account.type === 'credit_card'
  return (
    <div className="rounded-2xl px-4 py-4 text-white" style={{ backgroundColor: account.color }}>
      <div className="flex items-center justify-between mb-2">
        <span className="text-sm font-medium opacity-80 truncate">{account.name}</span>
        <span className="text-lg shrink-0 ml-2" aria-hidden="true">{isCredit ? '💳' : '🏦'}</span>
      </div>
      <p className="text-2xl font-bold leading-tight">{isCredit ? '-' : ''}{fmt(account.balance)}</p>
      <p className="text-xs opacity-70 mt-0.5">{isCredit ? 'owed' : 'available'}</p>
    </div>
  )
}

function SummaryCard({ label, value, color }: { label: string; value: string; color: 'emerald' | 'rose' | 'indigo' }) {
  const p: Record<string, string> = {
    emerald: 'bg-emerald-50 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-400',
    rose:    'bg-rose-50 dark:bg-rose-900/20 text-rose-700 dark:text-rose-400',
    indigo:  'bg-indigo-50 dark:bg-indigo-900/20 text-indigo-700 dark:text-indigo-400',
  }
  return (
    <div className={`rounded-2xl px-4 py-4 ${p[color]}`}>
      <p className="text-xs font-medium opacity-70 mb-1">{label}</p>
      <p className="text-xl font-bold leading-tight">{value}</p>
    </div>
  )
}

function RecentRow({ tx, catMap, fmt }: { tx: Transaction; catMap: Map<string, { icon?: string; name: string; color?: string }>; fmt: (n: number) => string }) {
  const cat = catMap.get(tx.categoryId)
  const isIncome = tx.type === 'income'
  return (
    <div className="flex items-center gap-3 px-4 py-3.5">
      <div className="w-9 h-9 rounded-xl flex items-center justify-center text-base shrink-0" style={{ backgroundColor: `${cat?.color ?? '#64748b'}20` }} aria-hidden="true">
        {cat?.icon ?? '📦'}
      </div>
      <div className="flex-1 min-w-0">
        <p className="text-sm font-medium text-slate-900 dark:text-white truncate">{tx.merchant || cat?.name || 'Unknown'}</p>
        <p className="text-xs text-slate-500 dark:text-slate-400">{tx.date}</p>
      </div>
      <span className={`text-sm font-semibold shrink-0 ${isIncome ? 'text-emerald-600 dark:text-emerald-400' : 'text-slate-900 dark:text-white'}`}>
        {isIncome ? '+' : '-'}{fmt(tx.amount)}
      </span>
    </div>
  )
}
