// Generated by GitHub Copilot
import { useMemo, useState } from "react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Legend,
  Line,
  LineChart,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { useStorage } from "../hooks/useStorage";
import { useTransactions } from "../hooks/useTransactions";
import { useCategories } from "../hooks/useCategories";
import { formatCurrency } from "../utils/currency";
import { addMonths, formatMonthYear, getCurrentMonth } from "../utils/date";

const CHART_COLORS = [
  "#6366f1",
  "#8b5cf6",
  "#f97316",
  "#10b981",
  "#ef4444",
  "#eab308",
  "#14b8a6",
  "#ec4899",
];

export default function ReportsPage() {
  const { settings } = useStorage();
  const { transactions } = useTransactions();
  const categories = useCategories();
  const [month, setMonth] = useState(getCurrentMonth());

  const catMap = useMemo(
    () => new Map(categories.map((c) => [c.id, c])),
    [categories],
  );

  const chartData = useMemo(() => {
    const months: Array<{ month: string; income: number; expense: number }> =
      [];
    let cursor = month;
    for (let i = 5; i >= 0; i--) {
      cursor = addMonths(month, -i);
      const monthTxs = transactions.filter((tx) => tx.date.startsWith(cursor));
      const income = monthTxs
        .filter((tx) => tx.type === "income")
        .reduce((sum, tx) => sum + tx.amount, 0);
      const expense = monthTxs
        .filter((tx) => tx.type === "expense")
        .reduce((sum, tx) => sum + tx.amount, 0);
      months.push({ month: cursor, income, expense });
    }
    return months;
  }, [transactions, month]);

  const categoryBreakdown = useMemo(() => {
    const monthTxs = transactions.filter(
      (tx) =>
        tx.date.startsWith(month) && tx.type === "expense" && tx.categoryId,
    );
    const totals = new Map<string, number>();

    for (const tx of monthTxs) {
      if (!tx.categoryId) continue;
      totals.set(tx.categoryId, (totals.get(tx.categoryId) ?? 0) + tx.amount);
    }

    return Array.from(totals.entries())
      .map(([categoryId, amount]) => ({
        name: catMap.get(categoryId)?.name ?? "Unknown",
        value: amount,
        color: catMap.get(categoryId)?.color ?? "#64748b",
      }))
      .sort((a, b) => b.value - a.value);
  }, [transactions, month, catMap]);

  const currencyFmt = (
    n: number | string | readonly (number | string)[] | undefined,
  ) => {
    const numeric = Array.isArray(n) ? Number(n[0] ?? 0) : Number(n ?? 0);
    return formatCurrency(numeric, settings.currencySymbol, settings.locale);
  };

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-slate-900 dark:text-white">
          Reports
        </h1>
      </div>

      <div className="flex items-center justify-between bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl px-4 py-3">
        <button
          type="button"
          onClick={() => setMonth((m) => addMonths(m, -1))}
          aria-label="Previous month"
          className="w-9 h-9 flex items-center justify-center rounded-xl text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
        >
          <svg
            width={20}
            height={20}
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth={2}
            strokeLinecap="round"
            aria-hidden="true"
          >
            <path d="M15 18l-6-6 6-6" />
          </svg>
        </button>
        <span className="text-sm font-semibold text-slate-900 dark:text-white">
          {formatMonthYear(month)}
        </span>
        <button
          type="button"
          onClick={() => setMonth((m) => addMonths(m, 1))}
          aria-label="Next month"
          className="w-9 h-9 flex items-center justify-center rounded-xl text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
        >
          <svg
            width={20}
            height={20}
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth={2}
            strokeLinecap="round"
            aria-hidden="true"
          >
            <path d="M9 18l6-6-6-6" />
          </svg>
        </button>
      </div>

      {transactions.length === 0 ? (
        <div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-8 text-center">
          <span className="text-4xl" aria-hidden="true">
            📊
          </span>
          <p className="mt-3 font-semibold text-slate-700 dark:text-slate-300">
            No data yet
          </p>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
            Add transactions to unlock monthly trends and category insights.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          <ChartCard title="Spending by month (last 6 months)">
            <div className="h-72">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={chartData}>
                  <CartesianGrid
                    strokeDasharray="3 3"
                    stroke="#94a3b8"
                    opacity={0.25}
                  />
                  <XAxis dataKey="month" tick={{ fontSize: 12 }} />
                  <YAxis tick={{ fontSize: 12 }} />
                  <Tooltip formatter={(value) => currencyFmt(value)} />
                  <Legend />
                  <Bar dataKey="income" fill="#10b981" radius={[6, 6, 0, 0]} />
                  <Bar dataKey="expense" fill="#ef4444" radius={[6, 6, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </ChartCard>

          <div className="grid gap-4 lg:grid-cols-2">
            <ChartCard title="Category breakdown">
              <div className="h-72">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={categoryBreakdown}
                      dataKey="value"
                      nameKey="name"
                      innerRadius={55}
                      outerRadius={82}
                      paddingAngle={2}
                    >
                      {categoryBreakdown.map((entry, index) => (
                        <Cell
                          key={`${entry.name}-${index}`}
                          fill={
                            entry.color ??
                            CHART_COLORS[index % CHART_COLORS.length]
                          }
                        />
                      ))}
                    </Pie>
                    <Tooltip formatter={(value) => currencyFmt(value)} />
                    <Legend />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            </ChartCard>

            <ChartCard title="Income vs expense trend">
              <div className="h-72">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={chartData}>
                    <CartesianGrid
                      strokeDasharray="3 3"
                      stroke="#94a3b8"
                      opacity={0.25}
                    />
                    <XAxis dataKey="month" tick={{ fontSize: 12 }} />
                    <YAxis tick={{ fontSize: 12 }} />
                    <Tooltip formatter={(value) => currencyFmt(value)} />
                    <Legend />
                    <Line
                      type="monotone"
                      dataKey="income"
                      stroke="#10b981"
                      strokeWidth={3}
                      dot={{ r: 3 }}
                    />
                    <Line
                      type="monotone"
                      dataKey="expense"
                      stroke="#ef4444"
                      strokeWidth={3}
                      dot={{ r: 3 }}
                    />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </ChartCard>
          </div>
        </div>
      )}
    </div>
  );
}

function ChartCard({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-4">
      <h2 className="text-sm font-semibold text-slate-900 dark:text-white mb-3">
        {title}
      </h2>
      {children}
    </section>
  );
}
