// Generated by GitHub Copilot
export default function ReportsPage() {
  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Reports</h1>

      <div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-8 text-center">
        <span className="text-4xl" aria-hidden="true">📊</span>
        <p className="mt-3 font-semibold text-slate-700 dark:text-slate-300">No data yet</p>
        <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
          Add transactions to see your spending charts and trends.
        </p>
      </div>
    </div>
  )
}
