// Generated by GitHub Copilot
import { useState, useRef } from 'react'
import { useStorage } from '../hooks/useStorage'
import { useAccounts } from '../hooks/useAccounts'
import { useCategories } from '../hooks/useCategories'
import BottomSheet from '../components/ui/BottomSheet'
import AccountForm from '../features/accounts/AccountForm'
import AccountCard from '../features/accounts/AccountCard'
import CategoryForm from '../features/categories/CategoryForm'
import CategoryCard from '../features/categories/CategoryCard'
import { PlusIcon } from '../components/icons/NavIcons'
import type { Account, Category, ThemeMode } from '../types'

const THEMES: { value: ThemeMode; label: string; emoji: string }[] = [
  { value: 'light',  label: 'Light',  emoji: '☀️' },
  { value: 'dark',   label: 'Dark',   emoji: '🌙' },
  { value: 'system', label: 'System', emoji: '🖥️' },
]

export default function SettingsPage() {
  const { storage, settings, refreshSettings } = useStorage()
  const { accounts, reload: reloadAccounts } = useAccounts()
  const { categories, reload: reloadCategories } = useCategories()
  const fileInputRef = useRef<HTMLInputElement>(null)

  const [accountSheetOpen, setAccountSheetOpen] = useState(false)
  const [editAccountTarget, setEditAccountTarget] = useState<Account | undefined>()

  const [catSheetOpen, setCatSheetOpen] = useState(false)
  const [editCatTarget, setEditCatTarget] = useState<Category | undefined>()

  function openAddAccount() { setEditAccountTarget(undefined); setAccountSheetOpen(true) }
  function openEditAccount(acc: Account) { setEditAccountTarget(acc); setAccountSheetOpen(true) }
  function handleAccountSuccess() { setAccountSheetOpen(false); reloadAccounts() }

  function openAddCategory() { setEditCatTarget(undefined); setCatSheetOpen(true) }
  function openEditCategory(cat: Category) { setEditCatTarget(cat); setCatSheetOpen(true) }
  function handleCategorySuccess() { setCatSheetOpen(false); reloadCategories() }

  async function handleTheme(theme: ThemeMode) {
    await storage.updateSettings({ theme })
    await refreshSettings()
  }

  async function handleExport() {
    try {
      const data = await storage.exportData()
      const jsonStr = JSON.stringify(data, null, 2)
      const blob = new Blob([jsonStr], { type: 'application/json' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      const date = new Date().toISOString().slice(0, 10)
      a.href = url
      a.download = `budget-tracker-backup-${date}.json`
      a.click()
      URL.revokeObjectURL(url)
    } catch (err) {
      alert('Failed to export data.')
    }
  }

  async function handleImportFile(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return
    try {
      const text = await file.text()
      const parsed = JSON.parse(text)
      if (!parsed.transactions || !parsed.settings) {
        alert('Invalid backup file structure.')
        return
      }
      if (window.confirm('Importing will replace your current transactions and data with the backup file. Proceed?')) {
        await storage.importData(parsed)
        alert('Data imported successfully!')
        window.location.reload()
      }
    } catch (err) {
      alert('Failed to parse backup file. Please ensure it is a valid JSON export.')
    }
    if (e.target) e.target.value = ''
  }

  async function handleResetAll() {
    if (window.confirm('Are you sure you want to delete all transactions and reset data? This action cannot be undone.')) {
      await storage.clearAll()
      await storage.initialize()
      alert('Data reset successfully.')
      window.location.reload()
    }
  }

  return (
    <>
      <div className="space-y-6">
        <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Settings</h1>

        {/* Categories */}
        <section className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden">
          <div className="flex items-center justify-between px-5 py-4 border-b border-slate-100 dark:border-slate-800">
            <div>
              <h2 className="font-semibold text-slate-900 dark:text-white">Categories</h2>
              <p className="text-xs text-slate-500 dark:text-slate-400">Customize income & expense categories</p>
            </div>
            <button
              type="button"
              onClick={openAddCategory}
              className="flex items-center gap-1.5 text-sm font-semibold text-indigo-600 dark:text-indigo-400 hover:text-indigo-700 dark:hover:text-indigo-300 transition-colors"
            >
              <PlusIcon size={16} />
              Add
            </button>
          </div>
          {categories.length === 0 ? (
            <div className="px-5 py-6 text-center">
              <p className="text-sm text-slate-500 dark:text-slate-400">No categories found.</p>
            </div>
          ) : (
            <div className="divide-y divide-slate-100 dark:divide-slate-800 max-h-96 overflow-y-auto">
              {categories.map(cat => (
                <CategoryCard key={cat.id} category={cat} onEdit={() => openEditCategory(cat)} />
              ))}
            </div>
          )}
        </section>

        {/* Accounts */}
        <section className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden">
          <div className="flex items-center justify-between px-5 py-4 border-b border-slate-100 dark:border-slate-800">
            <h2 className="font-semibold text-slate-900 dark:text-white">Accounts</h2>
            <button
              type="button"
              onClick={openAddAccount}
              className="flex items-center gap-1.5 text-sm font-semibold text-indigo-600 dark:text-indigo-400 hover:text-indigo-700 dark:hover:text-indigo-300 transition-colors"
            >
              <PlusIcon size={16} />
              Add
            </button>
          </div>
          {accounts.length === 0 ? (
            <div className="px-5 py-6 text-center">
              <p className="text-sm text-slate-500 dark:text-slate-400">No accounts yet. Add your bank accounts and cards.</p>
            </div>
          ) : (
            <div className="divide-y divide-slate-100 dark:divide-slate-800">
              {accounts.map(acc => (
                <AccountCard key={acc.id} account={acc} onEdit={() => openEditAccount(acc)} />
              ))}
            </div>
          )}
        </section>

        {/* Appearance */}
        <section className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden">
          <div className="px-5 py-4 border-b border-slate-100 dark:border-slate-800">
            <h2 className="font-semibold text-slate-900 dark:text-white">Appearance</h2>
          </div>
          <div className="px-5 py-4">
            <p className="text-sm text-slate-600 dark:text-slate-400 mb-3">Theme</p>
            <div className="flex gap-2" role="group" aria-label="Theme options">
              {THEMES.map(({ value, label, emoji }) => (
                <button
                  key={value}
                  type="button"
                  onClick={() => handleTheme(value)}
                  aria-pressed={settings.theme === value}
                  className={`flex flex-col items-center gap-1.5 flex-1 py-3 rounded-xl border-2 text-sm font-medium transition-colors ${
                    settings.theme === value
                      ? 'border-indigo-600 bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300'
                      : 'border-transparent bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700'
                  }`}
                >
                  <span className="text-xl" aria-hidden="true">{emoji}</span>
                  {label}
                </button>
              ))}
            </div>
          </div>
        </section>

        {/* Currency */}
        <section className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden">
          <div className="px-5 py-4 border-b border-slate-100 dark:border-slate-800">
            <h2 className="font-semibold text-slate-900 dark:text-white">Currency</h2>
          </div>
          <div className="flex items-center justify-between px-5 py-4">
            <span className="text-sm text-slate-600 dark:text-slate-400">Default currency</span>
            <span className="text-sm font-semibold text-slate-900 dark:text-white">
              {settings.currencySymbol} {settings.currency}
            </span>
          </div>
        </section>

        {/* Data */}
        <section className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden">
          <div className="px-5 py-4 border-b border-slate-100 dark:border-slate-800">
            <h2 className="font-semibold text-slate-900 dark:text-white">Data & Backup</h2>
          </div>
          <div className="divide-y divide-slate-100 dark:divide-slate-800">
            <button
              type="button"
              onClick={handleExport}
              className="w-full flex items-center justify-between px-5 py-4 text-sm font-medium text-slate-900 dark:text-white hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors text-left"
            >
              <div>
                <p className="font-semibold">Export Data</p>
                <p className="text-xs text-slate-500 dark:text-slate-400">Download a JSON backup of your transactions, accounts & budgets</p>
              </div>
              <span className="text-slate-400 text-base font-bold">↓</span>
            </button>

            <button
              type="button"
              onClick={() => fileInputRef.current?.click()}
              className="w-full flex items-center justify-between px-5 py-4 text-sm font-medium text-slate-900 dark:text-white hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors text-left"
            >
              <div>
                <p className="font-semibold">Import Data</p>
                <p className="text-xs text-slate-500 dark:text-slate-400">Restore your app data from a JSON backup file</p>
              </div>
              <span className="text-slate-400 text-base font-bold">↑</span>
            </button>
            <input
              ref={fileInputRef}
              type="file"
              accept=".json"
              onChange={handleImportFile}
              className="hidden"
            />

            <button
              type="button"
              onClick={handleResetAll}
              className="w-full flex items-center justify-between px-5 py-4 text-sm font-medium text-rose-600 dark:text-rose-400 hover:bg-rose-50 dark:hover:bg-rose-950/20 transition-colors text-left"
            >
              <div>
                <p className="font-semibold">Reset All Data</p>
                <p className="text-xs text-rose-500/80 dark:text-rose-400/70">Wipe all local data and restore default settings</p>
              </div>
              <span>⚠️</span>
            </button>
          </div>
        </section>
      </div>

      {/* Account Sheet */}
      <BottomSheet
        open={accountSheetOpen}
        onClose={() => setAccountSheetOpen(false)}
        title={editAccountTarget ? 'Edit Account' : 'Add Account'}
      >
        {accountSheetOpen && (
          <AccountForm account={editAccountTarget} onSuccess={handleAccountSuccess} />
        )}
      </BottomSheet>

      {/* Category Sheet */}
      <BottomSheet
        open={catSheetOpen}
        onClose={() => setCatSheetOpen(false)}
        title={editCatTarget ? 'Edit Category' : 'Add Category'}
      >
        {catSheetOpen && (
          <CategoryForm category={editCatTarget} onSuccess={handleCategorySuccess} />
        )}
      </BottomSheet>
    </>
  )
}
