// Generated by GitHub Copilot
import { useState } from 'react'
import { useStorage } from '../hooks/useStorage'
import { useAccounts } from '../hooks/useAccounts'
import { useCategories } from '../hooks/useCategories'
import BottomSheet from '../components/ui/BottomSheet'
import AccountForm from '../features/accounts/AccountForm'
import AccountCard from '../features/accounts/AccountCard'
import CategoryForm from '../features/categories/CategoryForm'
import CategoryCard from '../features/categories/CategoryCard'
import { PlusIcon } from '../components/icons/NavIcons'
import type { Account, Category, ThemeMode } from '../types'

const THEMES: { value: ThemeMode; label: string; emoji: string }[] = [
  { value: 'light',  label: 'Light',  emoji: '☀️' },
  { value: 'dark',   label: 'Dark',   emoji: '🌙' },
  { value: 'system', label: 'System', emoji: '🖥️' },
]

export default function SettingsPage() {
  const { storage, settings, refreshSettings } = useStorage()
  const { accounts, reload: reloadAccounts } = useAccounts()
  const { categories, reload: reloadCategories } = useCategories()

  const [accountSheetOpen, setAccountSheetOpen] = useState(false)
  const [editAccountTarget, setEditAccountTarget] = useState<Account | undefined>()

  const [catSheetOpen, setCatSheetOpen] = useState(false)
  const [editCatTarget, setEditCatTarget] = useState<Category | undefined>()

  function openAddAccount() { setEditAccountTarget(undefined); setAccountSheetOpen(true) }
  function openEditAccount(acc: Account) { setEditAccountTarget(acc); setAccountSheetOpen(true) }
  function handleAccountSuccess() { setAccountSheetOpen(false); reloadAccounts() }

  function openAddCategory() { setEditCatTarget(undefined); setCatSheetOpen(true) }
  function openEditCategory(cat: Category) { setEditCatTarget(cat); setCatSheetOpen(true) }
  function handleCategorySuccess() { setCatSheetOpen(false); reloadCategories() }

  async function handleTheme(theme: ThemeMode) {
    await storage.updateSettings({ theme })
    await refreshSettings()
  }

  return (
    <>
      <div className="space-y-6">
        <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Settings</h1>

        {/* Categories */}
        <section className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden">
          <div className="flex items-center justify-between px-5 py-4 border-b border-slate-100 dark:border-slate-800">
            <div>
              <h2 className="font-semibold text-slate-900 dark:text-white">Categories</h2>
              <p className="text-xs text-slate-500 dark:text-slate-400">Customize income & expense categories</p>
            </div>
            <button
              type="button"
              onClick={openAddCategory}
              className="flex items-center gap-1.5 text-sm font-semibold text-indigo-600 dark:text-indigo-400 hover:text-indigo-700 dark:hover:text-indigo-300 transition-colors"
            >
              <PlusIcon size={16} />
              Add
            </button>
          </div>
          {categories.length === 0 ? (
            <div className="px-5 py-6 text-center">
              <p className="text-sm text-slate-500 dark:text-slate-400">No categories found.</p>
            </div>
          ) : (
            <div className="divide-y divide-slate-100 dark:divide-slate-800 max-h-96 overflow-y-auto">
              {categories.map(cat => (
                <CategoryCard key={cat.id} category={cat} onEdit={() => openEditCategory(cat)} />
              ))}
            </div>
          )}
        </section>

        {/* Accounts */}
        <section className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden">
          <div className="flex items-center justify-between px-5 py-4 border-b border-slate-100 dark:border-slate-800">
            <h2 className="font-semibold text-slate-900 dark:text-white">Accounts</h2>
            <button
              type="button"
              onClick={openAddAccount}
              className="flex items-center gap-1.5 text-sm font-semibold text-indigo-600 dark:text-indigo-400 hover:text-indigo-700 dark:hover:text-indigo-300 transition-colors"
            >
              <PlusIcon size={16} />
              Add
            </button>
          </div>
          {accounts.length === 0 ? (
            <div className="px-5 py-6 text-center">
              <p className="text-sm text-slate-500 dark:text-slate-400">No accounts yet. Add your bank accounts and cards.</p>
            </div>
          ) : (
            <div className="divide-y divide-slate-100 dark:divide-slate-800">
              {accounts.map(acc => (
                <AccountCard key={acc.id} account={acc} onEdit={() => openEditAccount(acc)} />
              ))}
            </div>
          )}
        </section>

        {/* Appearance */}
        <section className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden">
          <div className="px-5 py-4 border-b border-slate-100 dark:border-slate-800">
            <h2 className="font-semibold text-slate-900 dark:text-white">Appearance</h2>
          </div>
          <div className="px-5 py-4">
            <p className="text-sm text-slate-600 dark:text-slate-400 mb-3">Theme</p>
            <div className="flex gap-2" role="group" aria-label="Theme options">
              {THEMES.map(({ value, label, emoji }) => (
                <button
                  key={value}
                  type="button"
                  onClick={() => handleTheme(value)}
                  aria-pressed={settings.theme === value}
                  className={`flex flex-col items-center gap-1.5 flex-1 py-3 rounded-xl border-2 text-sm font-medium transition-colors ${
                    settings.theme === value
                      ? 'border-indigo-600 bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300'
                      : 'border-transparent bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700'
                  }`}
                >
                  <span className="text-xl" aria-hidden="true">{emoji}</span>
                  {label}
                </button>
              ))}
            </div>
          </div>
        </section>

        {/* Currency */}
        <section className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden">
          <div className="px-5 py-4 border-b border-slate-100 dark:border-slate-800">
            <h2 className="font-semibold text-slate-900 dark:text-white">Currency</h2>
          </div>
          <div className="flex items-center justify-between px-5 py-4">
            <span className="text-sm text-slate-600 dark:text-slate-400">Default currency</span>
            <span className="text-sm font-semibold text-slate-900 dark:text-white">
              {settings.currencySymbol} {settings.currency}
            </span>
          </div>
        </section>

        {/* Data */}
        <section className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden">
          <div className="px-5 py-4 border-b border-slate-100 dark:border-slate-800">
            <h2 className="font-semibold text-slate-900 dark:text-white">Data</h2>
          </div>
          <div className="divide-y divide-slate-100 dark:divide-slate-800">
            {['Export data', 'Import data', 'Reset all data'].map(label => (
              <button key={label} type="button" disabled className="w-full text-left px-5 py-4 text-sm text-slate-400 dark:text-slate-600 cursor-not-allowed" aria-disabled="true">
                {label} <span className="text-xs">(coming soon)</span>
              </button>
            ))}
          </div>
        </section>
      </div>

      {/* Account Sheet */}
      <BottomSheet
        open={accountSheetOpen}
        onClose={() => setAccountSheetOpen(false)}
        title={editAccountTarget ? 'Edit Account' : 'Add Account'}
      >
        {accountSheetOpen && (
          <AccountForm account={editAccountTarget} onSuccess={handleAccountSuccess} />
        )}
      </BottomSheet>

      {/* Category Sheet */}
      <BottomSheet
        open={catSheetOpen}
        onClose={() => setCatSheetOpen(false)}
        title={editCatTarget ? 'Edit Category' : 'Add Category'}
      >
        {catSheetOpen && (
          <CategoryForm category={editCatTarget} onSuccess={handleCategorySuccess} />
        )}
      </BottomSheet>
    </>
  )
}
