// Generated by GitHub Copilot
import { useState, useMemo } from 'react'
import { PlusIcon } from '../components/icons/NavIcons'
import { useTransactions } from '../hooks/useTransactions'
import { useCategories } from '../hooks/useCategories'
import { useAccounts } from '../hooks/useAccounts'
import { useParentBudgets } from '../hooks/useParentBudgets'
import { useStorage } from '../hooks/useStorage'
import BottomSheet from '../components/ui/BottomSheet'
import TransactionForm from '../features/transactions/TransactionForm'
import TransactionList from '../features/transactions/TransactionList'
import type { Transaction } from '../types'

export default function TransactionsPage() {
  const { settings } = useStorage()
  const { transactions, loading, reload } = useTransactions()
  const { categories } = useCategories()
  const { accounts } = useAccounts()
  const { parentBudgets } = useParentBudgets()

  /** Unique merchants sorted by how often they appear (most frequent first). */
  const merchants = useMemo(() => {
    const freq = new Map<string, number>()
    for (const tx of transactions) {
      if (!tx.merchant) continue
      freq.set(tx.merchant, (freq.get(tx.merchant) ?? 0) + 1)
    }
    return Array.from(freq.entries())
      .sort((a, b) => b[1] - a[1])
      .map(([name]) => name)
  }, [transactions])
  const [sheetOpen, setSheetOpen] = useState(false)
  const [editTarget, setEditTarget] = useState<Transaction | undefined>()

  function openAdd() {
    setEditTarget(undefined)
    setSheetOpen(true)
  }

  function openEdit(tx: Transaction) {
    setEditTarget(tx)
    setSheetOpen(true)
  }

  function handleSuccess() {
    setSheetOpen(false)
    reload()
  }

  return (
    <>
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Transactions</h1>
          <button
            type="button"
            onClick={openAdd}
            className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 text-white px-4 py-2.5 rounded-xl text-sm font-semibold transition-colors min-h-[44px]"
          >
            <PlusIcon size={18} />
            Add
          </button>
        </div>

        {loading ? (
          <div className="flex justify-center py-12" role="status" aria-label="Loading transactions">
            <div className="w-8 h-8 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin" />
          </div>
        ) : (
          <TransactionList
            transactions={transactions}
            categories={categories}
            accounts={accounts}
            currencySymbol={settings.currencySymbol}
            locale={settings.locale}
            onEditTransaction={openEdit}
          />
        )}
      </div>

      <BottomSheet
        open={sheetOpen}
        onClose={() => setSheetOpen(false)}
        title={editTarget ? 'Edit Transaction' : 'Add Transaction'}
      >
        {sheetOpen && (
          <TransactionForm
            categories={categories}
            accounts={accounts}
            budgets={parentBudgets}
            merchants={merchants}
            transaction={editTarget}
            onSuccess={handleSuccess}
          />
        )}
      </BottomSheet>
    </>
  )
}
