// Generated by GitHub Copilot

/** Format a number as a currency string using the configured symbol and locale. */
export function formatCurrency(
  amount: number,
  currencySymbol: string,
  locale: string,
): string {
  const formatted = new Intl.NumberFormat(locale, {
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(Math.abs(amount))
  return `${currencySymbol}${formatted}`
}
