// Generated by GitHub Copilot

export function formatDate(dateStr: string, locale = 'en-IN'): string {
  return new Date(`${dateStr}T00:00:00`).toLocaleDateString(locale, {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  })
}

export function formatDayMonth(dateStr: string, locale = 'en-IN'): string {
  return new Date(`${dateStr}T00:00:00`).toLocaleDateString(locale, {
    day: 'numeric',
    month: 'short',
  })
}

export function formatMonthYear(month: string): string {
  const [year, m] = month.split('-')
  return new Date(Number(year), Number(m) - 1).toLocaleDateString('en-IN', {
    month: 'long',
    year: 'numeric',
  })
}

/** Returns the current month as YYYY-MM. */
export function getCurrentMonth(): string {
  const d = new Date()
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
}

/** Returns today as YYYY-MM-DD. */
export function getTodayISO(): string {
  return new Date().toISOString().slice(0, 10)
}

/** Shift a YYYY-MM month string by delta months. */
export function addMonths(month: string, delta: number): string {
  const [y, m] = month.split('-').map(Number)
  const d = new Date(y, m - 1 + delta, 1)
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
}
