// Generated by GitHub Copilot

export function formatDate(dateStr: string, locale = 'en-IN'): string {
  return new Date(`${dateStr}T00:00:00`).toLocaleDateString(locale, {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  })
}

export function formatDayMonth(dateStr: string, locale = 'en-IN'): string {
  return new Date(`${dateStr}T00:00:00`).toLocaleDateString(locale, {
    day: 'numeric',
    month: 'short',
  })
}

export function formatMonthYear(month: string): string {
  const [year, m] = month.split('-')
  return new Date(Number(year), Number(m) - 1).toLocaleDateString('en-IN', {
    month: 'long',
    year: 'numeric',
  })
}

/** Returns the current month as YYYY-MM. */
export function getCurrentMonth(): string {
  const d = new Date()
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
}

/** Returns a local YYYY-MM-DD string for a given Date object. */
export function toLocalDateString(d: Date = new Date()): string {
  const year = d.getFullYear()
  const month = String(d.getMonth() + 1).padStart(2, '0')
  const day = String(d.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

/** Returns today as local YYYY-MM-DD. */
export function getTodayISO(): string {
  return toLocalDateString(new Date())
}

/** Returns yesterday as local YYYY-MM-DD. */
export function getYesterdayISO(): string {
  const d = new Date()
  d.setDate(d.getDate() - 1)
  return toLocalDateString(d)
}

/** Shift a YYYY-MM month string by delta months. */
export function addMonths(month: string, delta: number): string {
  const [y, m] = month.split('-').map(Number)
  const d = new Date(y, m - 1 + delta, 1)
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
}
/** Formats ISO timestamp or date-time string to 24h local time (e.g. 14:30 / 00:31). */
export function formatTime(dateStr?: string, locale = 'en-IN'): string {
  if (!dateStr) return ''
  const d = new Date(dateStr)
  if (isNaN(d.getTime())) return ''
  return d.toLocaleTimeString(locale, { hour: '2-digit', minute: '2-digit', hour12: false })
}

/** Returns current local time as HH:mm string. */
export function getCurrentTime24(): string {
  const d = new Date()
  const hours = String(d.getHours()).padStart(2, '0')
  const minutes = String(d.getMinutes()).padStart(2, '0')
  return `${hours}:${minutes}`
}

/** Extracts HH:mm local time string from an ISO timestamp or date string. */
export function getTime24FromDate(dateStr?: string): string {
  if (!dateStr) return getCurrentTime24()
  const d = new Date(dateStr)
  if (isNaN(d.getTime())) return getCurrentTime24()
  const hours = String(d.getHours()).padStart(2, '0')
  const minutes = String(d.getMinutes()).padStart(2, '0')
  return `${hours}:${minutes}`
}

import type { ParentBudget } from '../types'

export interface BudgetPeriodStats {
  daysElapsed: number
  daysRemaining: number
  totalDays: number
  isOngoing: boolean
}

/** Computes period stats (days elapsed, days remaining, active status) for a budget. */
export function getBudgetPeriodStats(b: ParentBudget): BudgetPeriodStats {
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  const todayTime = today.getTime()

  let startDate: Date
  let endDate: Date

  const type = b.budgetType ?? 'custom'
  if (type === 'monthly' && b.month) {
    const [year, m] = b.month.split('-').map(Number)
    startDate = new Date(year, m - 1, 1)
    endDate = new Date(year, m, 0)
  } else if (b.startDate && b.endDate) {
    const [sy, sm, sd] = b.startDate.split('-').map(Number)
    const [ey, em, ed] = b.endDate.split('-').map(Number)
    startDate = new Date(sy, sm - 1, sd)
    endDate = new Date(ey, em - 1, ed)
  } else {
    const now = new Date()
    startDate = new Date(now.getFullYear(), now.getMonth(), 1)
    endDate = new Date(now.getFullYear(), now.getMonth() + 1, 0)
  }

  startDate.setHours(0, 0, 0, 0)
  endDate.setHours(0, 0, 0, 0)

  const startTime = startDate.getTime()
  const endTime = endDate.getTime()
  const totalDays = Math.max(1, Math.round((endTime - startTime) / 86400000) + 1)

  if (todayTime < startTime) {
    return { daysElapsed: 0, daysRemaining: totalDays, totalDays, isOngoing: false }
  } else if (todayTime > endTime) {
    return { daysElapsed: totalDays, daysRemaining: 0, totalDays, isOngoing: false }
  } else {
    const daysElapsed = Math.max(1, Math.round((todayTime - startTime) / 86400000) + 1)
    const daysRemaining = Math.max(1, Math.round((endTime - todayTime) / 86400000) + 1)
    return { daysElapsed, daysRemaining, totalDays, isOngoing: true }
  }
}

