// Generated by GitHub Copilot

export function formatDate(dateStr: string, locale = 'en-IN'): string {
  return new Date(`${dateStr}T00:00:00`).toLocaleDateString(locale, {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  })
}

export function formatDayMonth(dateStr: string, locale = 'en-IN'): string {
  return new Date(`${dateStr}T00:00:00`).toLocaleDateString(locale, {
    day: 'numeric',
    month: 'short',
  })
}

export function formatMonthYear(month: string): string {
  const [year, m] = month.split('-')
  return new Date(Number(year), Number(m) - 1).toLocaleDateString('en-IN', {
    month: 'long',
    year: 'numeric',
  })
}

/** Returns the current month as YYYY-MM. */
export function getCurrentMonth(): string {
  const d = new Date()
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
}

/** Returns a local YYYY-MM-DD string for a given Date object. */
export function toLocalDateString(d: Date = new Date()): string {
  const year = d.getFullYear()
  const month = String(d.getMonth() + 1).padStart(2, '0')
  const day = String(d.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

/** Returns today as local YYYY-MM-DD. */
export function getTodayISO(): string {
  return toLocalDateString(new Date())
}

/** Returns yesterday as local YYYY-MM-DD. */
export function getYesterdayISO(): string {
  const d = new Date()
  d.setDate(d.getDate() - 1)
  return toLocalDateString(d)
}

/** Shift a YYYY-MM month string by delta months. */
export function addMonths(month: string, delta: number): string {
  const [y, m] = month.split('-').map(Number)
  const d = new Date(y, m - 1 + delta, 1)
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
}

/** Formats ISO timestamp or date-time string to 24h local time (e.g. 14:30 / 00:31). */
export function formatTime(dateStr?: string, locale = 'en-IN'): string {
  if (!dateStr) return ''
  const d = new Date(dateStr)
  if (isNaN(d.getTime())) return ''
  return d.toLocaleTimeString(locale, { hour: '2-digit', minute: '2-digit', hour12: false })
}

