// Generated by GitHub Copilot
import type { Category, Settings } from '../types'

export const DEFAULT_SETTINGS: Settings = {
  id: 1,
  currency: 'INR',
  currencySymbol: '₹',
  locale: 'en-IN',
  theme: 'system',
}

export const DEFAULT_CATEGORIES: Omit<Category, 'id' | 'createdAt'>[] = [
  // Income
  { name: 'Salary',        type: 'income',  isDefault: true, color: '#10b981', icon: '💼' },
  { name: 'Freelance',     type: 'income',  isDefault: true, color: '#6366f1', icon: '💻' },
  { name: 'Investment',    type: 'income',  isDefault: true, color: '#f59e0b', icon: '📈' },
  { name: 'Gift',          type: 'income',  isDefault: true, color: '#ec4899', icon: '🎁' },
  { name: 'Refund',        type: 'income',  isDefault: true, color: '#14b8a6', icon: '↩️' },
  { name: 'Other Income',  type: 'income',  isDefault: true, color: '#64748b', icon: '💰' },
  // Expense
  { name: 'Food',          type: 'expense', isDefault: true, color: '#f97316', icon: '🍕' },
  { name: 'Groceries',     type: 'expense', isDefault: true, color: '#84cc16', icon: '🛒' },
  { name: 'Transport',     type: 'expense', isDefault: true, color: '#3b82f6', icon: '🚌' },
  { name: 'Fuel',          type: 'expense', isDefault: true, color: '#ef4444', icon: '⛽' },
  { name: 'Rent',          type: 'expense', isDefault: true, color: '#8b5cf6', icon: '🏠' },
  { name: 'Utilities',     type: 'expense', isDefault: true, color: '#06b6d4', icon: '💡' },
  { name: 'Shopping',      type: 'expense', isDefault: true, color: '#f43f5e', icon: '🛍️' },
  { name: 'Entertainment', type: 'expense', isDefault: true, color: '#a855f7', icon: '🎬' },
  { name: 'Healthcare',    type: 'expense', isDefault: true, color: '#22c55e', icon: '🏥' },
  { name: 'Education',     type: 'expense', isDefault: true, color: '#eab308', icon: '📚' },
  { name: 'Travel',        type: 'expense', isDefault: true, color: '#0ea5e9', icon: '✈️' },
  { name: 'Subscriptions', type: 'expense', isDefault: true, color: '#6366f1', icon: '🔔' },
  { name: 'Insurance',     type: 'expense', isDefault: true, color: '#94a3b8', icon: '🛡️' },
  { name: 'Investments',   type: 'expense', isDefault: true, color: '#10b981', icon: '📊' },
  { name: 'Gifts',         type: 'expense', isDefault: true, color: '#ec4899', icon: '🎁' },
  { name: 'Miscellaneous', type: 'expense', isDefault: true, color: '#64748b', icon: '📦' },
]
