// Generated by GitHub Copilot
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import type { ParentBudget } from '../../types'
import { useStorage } from '../../hooks/useStorage'
import { getCurrentMonth, getTodayISO } from '../../utils/date'

const schema = z
  .object({
    name: z.string().min(1, 'Name is required').max(60, 'Name is too long'),
    description: z.string().max(120, 'Description is too long').optional(),
    totalAmount: z
      .string()
      .min(1, 'Amount is required')
      .refine(v => /^\d+(\.\d{0,2})?$/.test(v) && parseFloat(v) > 0, 'Enter a positive amount'),
    budgetType: z.enum(['monthly', 'custom']),
    month: z.string().optional(),
    startDate: z.string().optional(),
    endDate: z.string().optional(),
  })
  .superRefine((data, ctx) => {
    if (data.budgetType === 'monthly' && !data.month) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['month'], message: 'Month is required' })
    }
    if (data.budgetType === 'custom') {
      if (!data.startDate)
        ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['startDate'], message: 'Start date is required' })
      if (!data.endDate)
        ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['endDate'], message: 'End date is required' })
      if (data.startDate && data.endDate && data.startDate > data.endDate)
        ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['endDate'], message: 'End date must be after start date' })
    }
  })

type FormValues = z.infer<typeof schema>

interface Props {
  budget?: ParentBudget
  onSuccess: () => void
}

/** Form to create or edit a ParentBudget (monthly or custom date range). */
export default function BudgetForm({ budget, onSuccess }: Props) {
  const { storage, settings } = useStorage()
  const today = getTodayISO()

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    formState: { errors, isSubmitting },
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
    defaultValues: {
      name: budget?.name ?? '',
      description: budget?.description ?? '',
      totalAmount: budget ? String(budget.totalAmount) : '',
      budgetType: budget?.budgetType ?? 'monthly',
      month: budget?.month ?? getCurrentMonth(),
      startDate: budget?.startDate ?? today,
      endDate: budget?.endDate ?? today,
    },
  })

  const budgetType = watch('budgetType')

  async function onSubmit(data: FormValues) {
    const payload: Omit<ParentBudget, 'id' | 'createdAt' | 'updatedAt'> = {
      name: data.name.trim(),
      description: data.description?.trim() || undefined,
      totalAmount: parseFloat(data.totalAmount),
      budgetType: data.budgetType,
      month: data.budgetType === 'monthly' ? data.month : undefined,
      startDate: data.budgetType === 'custom' ? data.startDate : undefined,
      endDate: data.budgetType === 'custom' ? data.endDate : undefined,
    }
    if (budget) {
      await storage.updateParentBudget(budget.id, payload)
    } else {
      await storage.addParentBudget(payload)
    }
    onSuccess()
  }

  async function handleDelete() {
    if (!budget) return
    await storage.deleteParentBudget(budget.id)
    onSuccess()
  }

  const inputCls = 'w-full px-4 py-3 bg-slate-50 dark:bg-slate-800 border-2 border-slate-200 dark:border-slate-700 rounded-xl focus:outline-none focus:border-indigo-500 dark:focus:border-indigo-400 text-slate-900 dark:text-white placeholder:text-slate-400 dark:placeholder:text-slate-600 transition-colors'

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-5" noValidate>
      {/* Budget type toggle */}
      <div>
        <p className="text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">Budget Type</p>
        <div className="flex rounded-xl overflow-hidden border-2 border-slate-200 dark:border-slate-700">
          {(['monthly', 'custom'] as const).map(t => (
            <button
              key={t}
              type="button"
              aria-pressed={budgetType === t}
              onClick={() => setValue('budgetType', t)}
              className={`flex-1 py-3 text-sm font-semibold transition-colors ${
                budgetType === t
                  ? 'bg-indigo-600 text-white'
                  : 'text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800'
              }`}
            >
              {t === 'monthly' ? '📅 Monthly' : '📆 Custom Range'}
            </button>
          ))}
        </div>
      </div>

      {/* Date field(s) */}
      {budgetType === 'monthly' ? (
        <div>
          <label htmlFor="budgetmonth" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5">Month</label>
          <input id="budgetmonth" type="month" {...register('month')} className={inputCls} />
          {errors.month && <p className="mt-1.5 text-xs text-rose-600 dark:text-rose-400" role="alert">{errors.month.message}</p>}
        </div>
      ) : (
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label htmlFor="budgetstartdate" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5">Start Date</label>
            <input id="budgetstartdate" type="date" {...register('startDate')} className={inputCls} />
            {errors.startDate && <p className="mt-1.5 text-xs text-rose-600 dark:text-rose-400" role="alert">{errors.startDate.message}</p>}
          </div>
          <div>
            <label htmlFor="budgetenddate" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5">End Date</label>
            <input id="budgetenddate" type="date" {...register('endDate')} className={inputCls} />
            {errors.endDate && <p className="mt-1.5 text-xs text-rose-600 dark:text-rose-400" role="alert">{errors.endDate.message}</p>}
          </div>
        </div>
      )}

      {/* Name */}
      <div>
        <label htmlFor="budgetname" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5">
          Budget Name
        </label>
        <input
          id="budgetname"
          type="text"
          placeholder="e.g. Goa Trip, Wedding, Monthly Goals"
          autoFocus
          autoComplete="off"
          {...register('name')}
          className={inputCls}
        />
        {errors.name && <p className="mt-1.5 text-xs text-rose-600 dark:text-rose-400" role="alert">{errors.name.message}</p>}
      </div>

      {/* Description */}
      <div>
        <label htmlFor="budgetdesc" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5">
          Description <span className="font-normal text-slate-400">(optional)</span>
        </label>
        <input
          id="budgetdesc"
          type="text"
          placeholder="Short note about this budget"
          autoComplete="off"
          {...register('description')}
          className={inputCls}
        />
        {errors.description && <p className="mt-1.5 text-xs text-rose-600 dark:text-rose-400" role="alert">{errors.description.message}</p>}
      </div>

      {/* Total Amount */}
      <div>
        <label htmlFor="budgetamt" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5">
          Total Budget
        </label>
        <div className="relative">
          <span className="absolute left-4 top-1/2 -translate-y-1/2 text-xl font-semibold text-slate-400 select-none" aria-hidden="true">
            {settings.currencySymbol}
          </span>
          <input
            id="budgetamt"
            type="text"
            inputMode="decimal"
            placeholder="0"
            autoComplete="off"
            {...register('totalAmount')}
            className="w-full pl-10 pr-4 py-3.5 text-2xl font-bold bg-slate-50 dark:bg-slate-800 border-2 border-slate-200 dark:border-slate-700 rounded-xl focus:outline-none focus:border-indigo-500 dark:focus:border-indigo-400 text-slate-900 dark:text-white placeholder:text-slate-300 dark:placeholder:text-slate-600 transition-colors"
          />
        </div>
        {errors.totalAmount && <p className="mt-1.5 text-xs text-rose-600 dark:text-rose-400" role="alert">{errors.totalAmount.message}</p>}
      </div>

      {/* Actions */}
      <div className="flex gap-3 pt-1">
        {budget && (
          <button
            type="button"
            onClick={handleDelete}
            aria-label="Delete budget"
            className="flex items-center justify-center w-12 h-12 rounded-xl bg-rose-50 dark:bg-rose-900/20 text-rose-600 dark:text-rose-400 hover:bg-rose-100 dark:hover:bg-rose-900/40 transition-colors shrink-0"
          >
            <svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
              <path d="M3 6h18M19 6l-1 14a2 2 0 01-2 2H8a2 2 0 01-2-2L5 6M10 11v6M14 11v6M9 6V4a1 1 0 011-1h4a1 1 0 011 1v2" />
            </svg>
          </button>
        )}
        <button
          type="submit"
          disabled={isSubmitting}
          className="flex-1 py-3.5 bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 disabled:opacity-60 text-white font-semibold rounded-xl transition-colors min-h-[48px]"
        >
          {isSubmitting ? 'Saving…' : budget ? 'Save Changes' : 'Create Budget'}
        </button>
      </div>
    </form>
  )
}

