// Generated by GitHub Copilot
import type { BudgetAllocation, Category } from '../../types'
import { formatCurrency } from '../../utils/currency'

interface Props {
  allocation: BudgetAllocation
  category: Category | undefined
  spent: number
  currencySymbol: string
  locale: string
  onClick: () => void
}

export default function BudgetProgress({ allocation, category, spent, currencySymbol, locale, onClick }: Props) {
  const pct = allocation.amount > 0 ? Math.min((spent / allocation.amount) * 100, 100) : 0
  const over = spent > allocation.amount
  const warn = !over && pct >= 80
  const fmt = (n: number) => formatCurrency(n, currencySymbol, locale)

  const barColor   = over ? 'bg-rose-500' : warn ? 'bg-amber-500' : 'bg-emerald-500'
  const valueColor = over
    ? 'text-rose-600 dark:text-rose-400'
    : warn
    ? 'text-amber-600 dark:text-amber-400'
    : 'text-slate-900 dark:text-white'

  return (
    <button
      type="button"
      onClick={onClick}
      className="w-full flex flex-col gap-2.5 px-5 py-4 hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors text-left"
    >
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-2 min-w-0">
          <span className="text-xl shrink-0" aria-hidden="true">{category?.icon ?? '📦'}</span>
          <span className="text-sm font-semibold text-slate-900 dark:text-white truncate">
            {category?.name ?? 'Unknown'}
          </span>
          {over && (
            <span className="shrink-0 text-[10px] font-bold text-rose-600 dark:text-rose-400 bg-rose-50 dark:bg-rose-900/30 px-1.5 py-0.5 rounded-full">
              OVER
            </span>
          )}
        </div>
        <div className="text-right shrink-0">
          <span className={`text-sm font-semibold ${valueColor}`}>{fmt(spent)}</span>
          <span className="text-xs text-slate-400 dark:text-slate-500"> / {fmt(allocation.amount)}</span>
        </div>
      </div>

      <div className="h-2 bg-slate-100 dark:bg-slate-700 rounded-full overflow-hidden">
        <div
          className={`h-full rounded-full transition-all duration-300 ${barColor}`}
          style={{ width: `${pct}%` }}
          role="progressbar"
          aria-valuenow={Math.round(pct)}
          aria-valuemin={0}
          aria-valuemax={100}
          aria-label={`${Math.round(pct)}% of allocation used`}
        />
      </div>
    </button>
  )
}
