// Generated by GitHub Copilot
import { useForm, Controller } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import type { BudgetAllocation, Category } from '../../types'
import { useStorage } from '../../hooks/useStorage'

const schema = z.object({
  categoryId: z.string().min(1, 'Please select a category'),
  amount: z
    .string()
    .min(1, 'Amount is required')
    .refine(v => /^\d+(\.\d{0,2})?$/.test(v) && parseFloat(v) > 0, 'Enter a positive amount'),
})

type FormValues = z.infer<typeof schema>

interface Props {
  budgetId: string
  allocation?: BudgetAllocation
  existingAllocations: BudgetAllocation[]
  categories: Category[]
  onSuccess: () => void
}

/** Form to add or edit a category allocation within a ParentBudget. */
export default function BudgetAllocationForm({ budgetId, allocation, existingAllocations, categories, onSuccess }: Props) {
  const { storage, settings } = useStorage()

  const {
    register,
    handleSubmit,
    control,
    formState: { errors, isSubmitting },
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
    defaultValues: {
      categoryId: allocation?.categoryId ?? '',
      amount: allocation ? String(allocation.amount) : '',
    },
  })

  async function onSubmit(data: FormValues) {
    // Prevent duplicate category in the same budget — update instead of insert
    const duplicate = existingAllocations.find(
      a => a.categoryId === data.categoryId && a.budgetId === budgetId && a.id !== allocation?.id,
    )
    if (allocation) {
      await storage.updateBudgetAllocation(allocation.id, {
        categoryId: data.categoryId,
        amount: parseFloat(data.amount),
      })
    } else if (duplicate) {
      await storage.updateBudgetAllocation(duplicate.id, { amount: parseFloat(data.amount) })
    } else {
      await storage.addBudgetAllocation({
        budgetId,
        categoryId: data.categoryId,
        amount: parseFloat(data.amount),
      })
    }
    onSuccess()
  }

  async function handleDelete() {
    if (!allocation) return
    await storage.deleteBudgetAllocation(allocation.id)
    onSuccess()
  }

  const expenseCategories = categories.filter(c => c.type === 'expense')

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-5" noValidate>
      {/* Category */}
      <div>
        <p className="text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">Category</p>
        <Controller
          control={control}
          name="categoryId"
          render={({ field }) => (
            <div>
              <div className="grid grid-cols-4 gap-2 sm:grid-cols-5" role="radiogroup" aria-label="Category">
                {expenseCategories.map(cat => (
                  <button
                    key={cat.id}
                    type="button"
                    role="radio"
                    aria-checked={field.value === cat.id}
                    onClick={() => field.onChange(cat.id)}
                    className={`flex flex-col items-center gap-1.5 py-3 px-1 rounded-xl border-2 transition-colors ${
                      field.value === cat.id
                        ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-900/30'
                        : 'border-transparent bg-slate-50 dark:bg-slate-800 hover:bg-slate-100 dark:hover:bg-slate-700'
                    }`}
                  >
                    <span className="text-2xl leading-none" aria-hidden="true">{cat.icon ?? '📦'}</span>
                    <span className="text-[10px] font-medium text-slate-700 dark:text-slate-300 text-center leading-tight line-clamp-1">
                      {cat.name}
                    </span>
                  </button>
                ))}
              </div>
              {errors.categoryId && (
                <p className="mt-1.5 text-xs text-rose-600 dark:text-rose-400" role="alert">{errors.categoryId.message}</p>
              )}
            </div>
          )}
        />
      </div>

      {/* Amount */}
      <div>
        <label htmlFor="allocamt" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5">
          Allocated Amount
        </label>
        <div className="relative">
          <span className="absolute left-4 top-1/2 -translate-y-1/2 text-xl font-semibold text-slate-400 select-none" aria-hidden="true">
            {settings.currencySymbol}
          </span>
          <input
            id="allocamt"
            type="text"
            inputMode="decimal"
            placeholder="0"
            autoFocus
            autoComplete="off"
            {...register('amount')}
            className="w-full pl-10 pr-4 py-3.5 text-2xl font-bold bg-slate-50 dark:bg-slate-800 border-2 border-slate-200 dark:border-slate-700 rounded-xl focus:outline-none focus:border-indigo-500 dark:focus:border-indigo-400 text-slate-900 dark:text-white placeholder:text-slate-300 dark:placeholder:text-slate-600 transition-colors"
          />
        </div>
        {errors.amount && <p className="mt-1.5 text-xs text-rose-600 dark:text-rose-400" role="alert">{errors.amount.message}</p>}
      </div>

      {/* Actions */}
      <div className="flex gap-3 pt-1">
        {allocation && (
          <button
            type="button"
            onClick={handleDelete}
            aria-label="Delete allocation"
            className="flex items-center justify-center w-12 h-12 rounded-xl bg-rose-50 dark:bg-rose-900/20 text-rose-600 dark:text-rose-400 hover:bg-rose-100 dark:hover:bg-rose-900/40 transition-colors shrink-0"
          >
            <svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
              <path d="M3 6h18M19 6l-1 14a2 2 0 01-2 2H8a2 2 0 01-2-2L5 6M10 11v6M14 11v6M9 6V4a1 1 0 011-1h4a1 1 0 011 1v2" />
            </svg>
          </button>
        )}
        <button
          type="submit"
          disabled={isSubmitting}
          className="flex-1 py-3.5 bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 disabled:opacity-60 text-white font-semibold rounded-xl transition-colors min-h-[48px]"
        >
          {isSubmitting ? 'Saving…' : allocation ? 'Save Changes' : 'Add Category'}
        </button>
      </div>
    </form>
  )
}
