// Generated by GitHub Copilot
import Dexie, { type Table } from 'dexie'
import type { Transaction, Category, Budget, Settings, AppMetadata, Account, ParentBudget, BudgetAllocation } from '../types'

export class BudgetDB extends Dexie {
  transactions!: Table<Transaction, string>
  categories!: Table<Category, string>
  budgets!: Table<Budget, string>
  accounts!: Table<Account, string>
  settings!: Table<Settings, number>
  metadata!: Table<AppMetadata, number>
  parentBudgets!: Table<ParentBudget, string>
  budgetAllocations!: Table<BudgetAllocation, string>

  constructor() {
    super('BudgetTrackerDB')
    // Never edit existing versions — only add new ones
    this.version(1).stores({
      transactions: 'id, type, date, categoryId, amount, *tags',
      categories: 'id, type, name',
      budgets: 'id, categoryId, month',
      settings: 'id',
      metadata: 'id',
    })
    this.version(2).stores({
      transactions: 'id, type, date, categoryId, accountId, amount, *tags',
      accounts: 'id, type, name',
    })
    this.version(3).stores({
      transactions: 'id, type, date, categoryId, accountId, toAccountId, amount, *tags',
    })
    // Version 4: parent budgets + allocations; transactions gain budgetId and drop *tags index
    this.version(4).stores({
      transactions: 'id, type, date, categoryId, accountId, toAccountId, amount, budgetId',
      parentBudgets: 'id, name',
      budgetAllocations: 'id, budgetId, categoryId',
    })
    // Version 5: index parentBudgets by budgetType and month for efficient filtering
    this.version(5).stores({
      parentBudgets: 'id, name, budgetType, month',
    })
  }
}

/** Singleton database instance shared across the app. */
export const db = new BudgetDB()
