// Generated by GitHub Copilot
import Dexie, { type Table } from 'dexie'
import type { Transaction, Category, Budget, Settings, AppMetadata, Account } from '../types'

export class BudgetDB extends Dexie {
  transactions!: Table<Transaction, string>
  categories!: Table<Category, string>
  budgets!: Table<Budget, string>
  accounts!: Table<Account, string>
  settings!: Table<Settings, number>
  metadata!: Table<AppMetadata, number>

  constructor() {
    super('BudgetTrackerDB')
    // Never edit existing versions — only add new ones
    this.version(1).stores({
      transactions: 'id, type, date, categoryId, amount, *tags',
      categories: 'id, type, name',
      budgets: 'id, categoryId, month',
      settings: 'id',
      metadata: 'id',
    })
    this.version(2).stores({
      transactions: 'id, type, date, categoryId, accountId, amount, *tags',
      accounts: 'id, type, name',
    })
    this.version(3).stores({
      transactions: 'id, type, date, categoryId, accountId, toAccountId, amount, *tags',
    })
  }
}

/** Singleton database instance shared across the app. */
export const db = new BudgetDB()
