// Generated by GitHub Copilot
import { db } from './db'
import type { StorageService } from './StorageService'
import type { Transaction, Category, Budget, Settings, Account, ExportData, AppMetadata, ParentBudget, BudgetAllocation } from '../types'
import { DEFAULT_SETTINGS, DEFAULT_CATEGORIES } from '../utils/defaults'

const now = () => new Date().toISOString()

// crypto.randomUUID requires a secure context (HTTPS); fall back for local HTTP dev
function uid(): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID()
  }
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
    const r = Math.random() * 16 | 0
    return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16)
  })
}

export class IndexedDBStorage implements StorageService {
  // Shared promise prevents duplicate seeding when StrictMode calls initialize() twice concurrently
  private initPromise: Promise<void> | null = null

  initialize(): Promise<void> {
    if (!this.initPromise) this.initPromise = this._seed()
    return this.initPromise
  }

  private async _seed(): Promise<void> {
    const [existing, catCount, meta] = await Promise.all([
      db.settings.get(1),
      db.categories.count(),
      db.metadata.get(1),
    ])

    const tasks: Promise<unknown>[] = []

    if (!existing) tasks.push(db.settings.put(DEFAULT_SETTINGS))

    if (catCount === 0) {
      const cats: Category[] = DEFAULT_CATEGORIES.map(c => ({
        ...c,
        id: uid(),
        createdAt: now(),
      }))
      tasks.push(db.categories.bulkPut(cats))
    }

    if (!meta) {
      tasks.push(
        db.metadata.put({ id: 1, schemaVersion: 1, createdAt: now() } satisfies AppMetadata),
      )
    }

    await Promise.all(tasks)
  }

  // --- Transactions ---

  async getTransactions(): Promise<Transaction[]> {
    const txs = await db.transactions.orderBy('date').reverse().toArray()
    return txs.sort((a, b) => {
      const timeA = new Date(a.createdAt || a.date).getTime()
      const timeB = new Date(b.createdAt || b.date).getTime()
      return timeB - timeA
    })
  }

  async getTransaction(id: string): Promise<Transaction | undefined> {
    return db.transactions.get(id)
  }

  async addTransaction(data: Omit<Transaction, 'id' | 'createdAt' | 'updatedAt'>): Promise<Transaction> {
    const tx: Transaction = { ...data, id: uid(), createdAt: now(), updatedAt: now() }
    await db.transactions.put(tx)
    await this._applyBalance(tx)
    return tx
  }

  async updateTransaction(id: string, updates: Partial<Omit<Transaction, 'id' | 'createdAt'>>): Promise<Transaction> {
    const existing = await db.transactions.get(id)
    if (!existing) throw new Error(`Transaction "${id}" not found`)
    await this._reverseBalance(existing)
    const updated: Transaction = { ...existing, ...updates, updatedAt: now() }
    await db.transactions.put(updated)
    await this._applyBalance(updated)
    return updated
  }

  async deleteTransaction(id: string): Promise<void> {
    const existing = await db.transactions.get(id)
    if (existing) await this._reverseBalance(existing)
    await db.transactions.delete(id)
  }

  private async _applyBalance(tx: Transaction): Promise<void> {
    if (tx.type === 'transfer') {
      if (tx.accountId)   await this._adjustBalance(tx.accountId,   -tx.amount)
      if (tx.toAccountId) await this._adjustBalance(tx.toAccountId,  tx.amount)
    } else {
      if (tx.accountId)   await this._adjustBalance(tx.accountId, tx.type === 'income' ? tx.amount : -tx.amount)
    }
  }

  private async _reverseBalance(tx: Transaction): Promise<void> {
    if (tx.type === 'transfer') {
      if (tx.accountId)   await this._adjustBalance(tx.accountId,    tx.amount)
      if (tx.toAccountId) await this._adjustBalance(tx.toAccountId, -tx.amount)
    } else {
      if (tx.accountId)   await this._adjustBalance(tx.accountId, tx.type === 'income' ? -tx.amount : tx.amount)
    }
  }

  private async _adjustBalance(accountId: string, delta: number): Promise<void> {
    const account = await db.accounts.get(accountId)
    if (!account) return
    const newBalance = Math.round((account.balance + delta) * 100) / 100
    await db.accounts.put({ ...account, balance: newBalance, updatedAt: now() })
  }

  // --- Categories ---

  async getCategories(): Promise<Category[]> {
    return db.categories.orderBy('name').toArray()
  }

  async getCategory(id: string): Promise<Category | undefined> {
    return db.categories.get(id)
  }

  async addCategory(data: Omit<Category, 'id' | 'createdAt'>): Promise<Category> {
    const cat: Category = { ...data, id: uid(), createdAt: now() }
    await db.categories.put(cat)
    return cat
  }

  async updateCategory(id: string, updates: Partial<Omit<Category, 'id' | 'createdAt'>>): Promise<Category> {
    const existing = await db.categories.get(id)
    if (!existing) throw new Error(`Category "${id}" not found`)
    const updated: Category = { ...existing, ...updates }
    await db.categories.put(updated)
    return updated
  }

  async deleteCategory(id: string): Promise<void> {
    await db.categories.delete(id)
  }

  // --- Budgets ---

  async getBudgets(month?: string): Promise<Budget[]> {
    if (month) return db.budgets.where('month').equals(month).toArray()
    return db.budgets.toArray()
  }

  async addBudget(data: Omit<Budget, 'id' | 'createdAt' | 'updatedAt'>): Promise<Budget> {
    const budget: Budget = { ...data, id: uid(), createdAt: now(), updatedAt: now() }
    await db.budgets.put(budget)
    return budget
  }

  async updateBudget(id: string, updates: Partial<Omit<Budget, 'id' | 'createdAt'>>): Promise<Budget> {
    const existing = await db.budgets.get(id)
    if (!existing) throw new Error(`Budget "${id}" not found`)
    const updated: Budget = { ...existing, ...updates, updatedAt: now() }
    await db.budgets.put(updated)
    return updated
  }

  async deleteBudget(id: string): Promise<void> {
    await db.budgets.delete(id)
  }

  // --- Parent Budgets ---

  async getParentBudgets(): Promise<ParentBudget[]> {
    return db.parentBudgets.orderBy('name').toArray()
  }

  async getParentBudget(id: string): Promise<ParentBudget | undefined> {
    return db.parentBudgets.get(id)
  }

  async addParentBudget(data: Omit<ParentBudget, 'id' | 'createdAt' | 'updatedAt'>): Promise<ParentBudget> {
    const budget: ParentBudget = { ...data, id: uid(), createdAt: now(), updatedAt: now() }
    await db.parentBudgets.put(budget)
    return budget
  }

  async updateParentBudget(id: string, updates: Partial<Omit<ParentBudget, 'id' | 'createdAt'>>): Promise<ParentBudget> {
    const existing = await db.parentBudgets.get(id)
    if (!existing) throw new Error(`ParentBudget "${id}" not found`)
    const updated: ParentBudget = { ...existing, ...updates, updatedAt: now() }
    await db.parentBudgets.put(updated)
    return updated
  }

  async deleteParentBudget(id: string): Promise<void> {
    // Cascade: remove allocations and unlink transactions
    await db.budgetAllocations.where('budgetId').equals(id).delete()
    await db.transactions.where('budgetId').equals(id).modify({ budgetId: undefined })
    await db.parentBudgets.delete(id)
  }

  // --- Budget Allocations ---

  async getBudgetAllocations(budgetId?: string): Promise<BudgetAllocation[]> {
    if (budgetId) return db.budgetAllocations.where('budgetId').equals(budgetId).toArray()
    return db.budgetAllocations.toArray()
  }

  async addBudgetAllocation(data: Omit<BudgetAllocation, 'id' | 'createdAt' | 'updatedAt'>): Promise<BudgetAllocation> {
    const allocation: BudgetAllocation = { ...data, id: uid(), createdAt: now(), updatedAt: now() }
    await db.budgetAllocations.put(allocation)
    return allocation
  }

  async updateBudgetAllocation(id: string, updates: Partial<Omit<BudgetAllocation, 'id' | 'createdAt'>>): Promise<BudgetAllocation> {
    const existing = await db.budgetAllocations.get(id)
    if (!existing) throw new Error(`BudgetAllocation "${id}" not found`)
    const updated: BudgetAllocation = { ...existing, ...updates, updatedAt: now() }
    await db.budgetAllocations.put(updated)
    return updated
  }

  async deleteBudgetAllocation(id: string): Promise<void> {
    await db.budgetAllocations.delete(id)
  }

  // --- Accounts ---

  async getAccounts(): Promise<Account[]> {
    return db.accounts.orderBy('name').toArray()
  }

  async getAccount(id: string): Promise<Account | undefined> {
    return db.accounts.get(id)
  }

  async addAccount(data: Omit<Account, 'id' | 'createdAt' | 'updatedAt'>): Promise<Account> {
    const account: Account = { ...data, id: uid(), createdAt: now(), updatedAt: now() }
    await db.accounts.put(account)
    return account
  }

  async updateAccount(id: string, updates: Partial<Omit<Account, 'id' | 'createdAt'>>): Promise<Account> {
    const existing = await db.accounts.get(id)
    if (!existing) throw new Error(`Account "${id}" not found`)
    const updated: Account = { ...existing, ...updates, updatedAt: now() }
    await db.accounts.put(updated)
    return updated
  }

  async deleteAccount(id: string): Promise<void> {
    await db.accounts.delete(id)
  }

  async getSettings(): Promise<Settings> {
    return (await db.settings.get(1)) ?? DEFAULT_SETTINGS
  }

  async updateSettings(updates: Partial<Omit<Settings, 'id'>>): Promise<Settings> {
    const current = await this.getSettings()
    const updated: Settings = { ...current, ...updates, id: 1 }
    await db.settings.put(updated)
    return updated
  }

  // --- Export / Import ---

  async exportData(): Promise<ExportData> {
    const [transactions, categories, budgets, settings, accounts, metadata, parentBudgets, budgetAllocations] = await Promise.all([
      this.getTransactions(),
      this.getCategories(),
      this.getBudgets(),
      this.getSettings(),
      this.getAccounts(),
      db.metadata.get(1),
      this.getParentBudgets(),
      this.getBudgetAllocations(),
    ])
    return {
      metadata: metadata ?? { id: 1, schemaVersion: 1, createdAt: now() },
      transactions,
      categories,
      budgets,
      parentBudgets,
      budgetAllocations,
      accounts,
      settings,
      exportedAt: now(),
    }
  }

  async importData(data: ExportData): Promise<void> {
    await db.transaction('rw', [db.transactions, db.categories, db.budgets, db.settings, db.metadata, db.accounts, db.parentBudgets, db.budgetAllocations], async () => {
      await Promise.all([
        db.transactions.clear(), db.categories.clear(), db.budgets.clear(),
        db.accounts.clear(), db.parentBudgets.clear(), db.budgetAllocations.clear(),
      ])
      await Promise.all([
        db.transactions.bulkPut(data.transactions),
        db.categories.bulkPut(data.categories),
        db.budgets.bulkPut(data.budgets),
        data.accounts?.length ? db.accounts.bulkPut(data.accounts) : Promise.resolve(),
        data.parentBudgets?.length ? db.parentBudgets.bulkPut(data.parentBudgets) : Promise.resolve(),
        data.budgetAllocations?.length ? db.budgetAllocations.bulkPut(data.budgetAllocations) : Promise.resolve(),
        db.settings.put(data.settings),
        db.metadata.put({ ...data.metadata, lastExportAt: now() }),
      ])
    })
  }

  async clearAll(): Promise<void> {
    await db.transaction('rw', [db.transactions, db.categories, db.budgets, db.settings, db.metadata, db.accounts, db.parentBudgets, db.budgetAllocations], async () => {
      await Promise.all([
        db.transactions.clear(), db.categories.clear(), db.budgets.clear(),
        db.accounts.clear(), db.settings.clear(), db.metadata.clear(),
        db.parentBudgets.clear(), db.budgetAllocations.clear(),
      ])
    })
    this.initPromise = null
    await this.initialize()
  }
}

/** Singleton storage instance — import this everywhere you need data access. */
export const storage = new IndexedDBStorage()
