// Generated by GitHub Copilot
import type { Transaction, Category, Budget, Settings, Account, ExportData, ParentBudget, BudgetAllocation } from '../types'

export interface StorageService {
  /** Seed defaults on first run. Safe to call multiple times. */
  initialize(): Promise<void>

  // --- Transactions ---
  getTransactions(): Promise<Transaction[]>
  getTransaction(id: string): Promise<Transaction | undefined>
  addTransaction(data: Omit<Transaction, 'id' | 'createdAt' | 'updatedAt'>): Promise<Transaction>
  updateTransaction(id: string, updates: Partial<Omit<Transaction, 'id' | 'createdAt'>>): Promise<Transaction>
  deleteTransaction(id: string): Promise<void>

  // --- Categories ---
  getCategories(): Promise<Category[]>
  getCategory(id: string): Promise<Category | undefined>
  addCategory(data: Omit<Category, 'id' | 'createdAt'>): Promise<Category>
  updateCategory(id: string, updates: Partial<Omit<Category, 'id' | 'createdAt'>>): Promise<Category>
  deleteCategory(id: string): Promise<void>

  // --- Budgets (legacy monthly limits) ---
  getBudgets(month?: string): Promise<Budget[]>
  addBudget(data: Omit<Budget, 'id' | 'createdAt' | 'updatedAt'>): Promise<Budget>
  updateBudget(id: string, updates: Partial<Omit<Budget, 'id' | 'createdAt'>>): Promise<Budget>
  deleteBudget(id: string): Promise<void>

  // --- Parent Budgets ---
  getParentBudgets(): Promise<ParentBudget[]>
  getParentBudget(id: string): Promise<ParentBudget | undefined>
  addParentBudget(data: Omit<ParentBudget, 'id' | 'createdAt' | 'updatedAt'>): Promise<ParentBudget>
  updateParentBudget(id: string, updates: Partial<Omit<ParentBudget, 'id' | 'createdAt'>>): Promise<ParentBudget>
  deleteParentBudget(id: string): Promise<void>

  // --- Budget Allocations ---
  getBudgetAllocations(budgetId?: string): Promise<BudgetAllocation[]>
  addBudgetAllocation(data: Omit<BudgetAllocation, 'id' | 'createdAt' | 'updatedAt'>): Promise<BudgetAllocation>
  updateBudgetAllocation(id: string, updates: Partial<Omit<BudgetAllocation, 'id' | 'createdAt'>>): Promise<BudgetAllocation>
  deleteBudgetAllocation(id: string): Promise<void>

  // --- Accounts ---
  getAccounts(): Promise<Account[]>
  getAccount(id: string): Promise<Account | undefined>
  addAccount(data: Omit<Account, 'id' | 'createdAt' | 'updatedAt'>): Promise<Account>
  updateAccount(id: string, updates: Partial<Omit<Account, 'id' | 'createdAt'>>): Promise<Account>
  deleteAccount(id: string): Promise<void>

  // --- Settings ---
  getSettings(): Promise<Settings>
  updateSettings(updates: Partial<Omit<Settings, 'id'>>): Promise<Settings>

  // --- Data management ---
  exportData(): Promise<ExportData>
  importData(data: ExportData): Promise<void>
  clearAll(): Promise<void>
}
