// Generated by GitHub Copilot
import { lazy, Suspense } from 'react'
import { createHashRouter, RouterProvider } from 'react-router-dom'
import { StorageProvider } from './contexts/StorageContext'
import Layout from './components/layout/Layout'

// Lazy-load pages so each route chunk is only downloaded when first visited
const DashboardPage    = lazy(() => import('./pages/DashboardPage'))
const TransactionsPage = lazy(() => import('./pages/TransactionsPage'))
const BudgetsPage      = lazy(() => import('./pages/BudgetsPage'))
const ReportsPage      = lazy(() => import('./pages/ReportsPage'))
const SettingsPage     = lazy(() => import('./pages/SettingsPage'))

function PageSpinner() {
  return (
    <div className="flex items-center justify-center py-16" role="status" aria-label="Loading page">
      <div className="w-8 h-8 rounded-full border-2 border-indigo-500 border-t-transparent animate-spin" />
    </div>
  )
}

// createHashRouter — required for static hosts like GitHub Pages (no server-side routing)
const router = createHashRouter([
  {
    path: '/',
    element: <Layout />,
    children: [
      { index: true,          element: <Suspense fallback={<PageSpinner />}><DashboardPage /></Suspense> },
      { path: 'transactions', element: <Suspense fallback={<PageSpinner />}><TransactionsPage /></Suspense> },
      { path: 'budgets',      element: <Suspense fallback={<PageSpinner />}><BudgetsPage /></Suspense> },
      { path: 'reports',      element: <Suspense fallback={<PageSpinner />}><ReportsPage /></Suspense> },
      { path: 'settings',     element: <Suspense fallback={<PageSpinner />}><SettingsPage /></Suspense> },
    ],
  },
])

export default function App() {
  return (
    <StorageProvider>
      <RouterProvider router={router} />
    </StorageProvider>
  )
}
