// Generated by GitHub Copilot
import type { Category } from '../../types'

interface Props {
  categories: Category[]
  value: string
  type: 'income' | 'expense'
  onChange: (id: string) => void
  error?: string
}

export default function CategoryPicker({ categories, value, type, onChange, error }: Props) {
  const filtered = categories.filter(c => c.type === type)

  return (
    <div>
      <div className="grid grid-cols-4 gap-2 sm:grid-cols-5" role="radiogroup" aria-label="Category">
        {filtered.map(cat => (
          <button
            key={cat.id}
            type="button"
            role="radio"
            aria-checked={value === cat.id}
            onClick={() => onChange(cat.id)}
            className={`flex flex-col items-center gap-1.5 py-3 px-1 rounded-xl border-2 transition-colors ${
              value === cat.id
                ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-900/30'
                : 'border-transparent bg-slate-50 dark:bg-slate-800 hover:bg-slate-100 dark:hover:bg-slate-700'
            }`}
          >
            <span className="text-2xl leading-none" aria-hidden="true">{cat.icon ?? '📦'}</span>
            <span className="text-[10px] font-medium text-slate-700 dark:text-slate-300 text-center leading-tight line-clamp-1">
              {cat.name}
            </span>
          </button>
        ))}
      </div>
      {error && <p className="mt-1.5 text-xs text-rose-600 dark:text-rose-400" role="alert">{error}</p>}
    </div>
  )
}
