// Generated by GitHub Copilot
import type { Transaction, Category, Account } from '../../types'
import { formatCurrency } from '../../utils/currency'

interface Props {
  transaction: Transaction
  category: Category | undefined
  toAccount: Account | undefined
  currencySymbol: string
  locale: string
  onClick: () => void
}

export default function TransactionItem({ transaction, category, toAccount, currencySymbol, locale, onClick }: Props) {
  const isTransfer = transaction.type === 'transfer'
  const isIncome   = transaction.type === 'income'
  const amount = formatCurrency(transaction.amount, currencySymbol, locale)

  const icon  = isTransfer ? '⇄' : (category?.icon ?? '📦')
  const color = isTransfer ? '#6366f1' : (category?.color ?? '#64748b')
  const label = isTransfer
    ? (toAccount ? `To ${toAccount.name}` : 'Transfer')
    : (transaction.merchant || category?.name || 'Unknown')
  const sub = isTransfer
    ? transaction.notes
    : (!transaction.notes && transaction.merchant ? category?.name : transaction.notes)

  return (
    <button
      type="button"
      onClick={onClick}
      className="w-full flex items-center gap-3 px-4 py-3.5 hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors text-left"
    >
      <div
        className="w-10 h-10 rounded-xl flex items-center justify-center text-xl shrink-0"
        style={{ backgroundColor: `${color}20` }}
        aria-hidden="true"
      >
        {icon}
      </div>

      <div className="flex-1 min-w-0">
        <p className="text-sm font-medium text-slate-900 dark:text-white leading-tight truncate">{label}</p>
        {sub && <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5 truncate">{sub}</p>}
      </div>

      <span className={`text-sm font-semibold shrink-0 ${
        isTransfer ? 'text-indigo-600 dark:text-indigo-400'
        : isIncome  ? 'text-emerald-600 dark:text-emerald-400'
        :             'text-slate-900 dark:text-white'
      }`}>
        {isTransfer ? '' : isIncome ? '+' : '-'}{amount}
      </span>
    </button>
  )
}
