// Generated by GitHub Copilot
import { useForm, Controller } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import type { Transaction, Category, Account, ParentBudget } from '../../types'
import { useStorage } from '../../hooks/useStorage'
import { getTodayISO } from '../../utils/date'
import CategoryPicker from './CategoryPicker'
import MerchantInput from '../../components/ui/MerchantInput'

const schema = z
  .object({
    type: z.enum(['income', 'expense', 'transfer']),
    amount: z
      .string()
      .min(1, 'Amount is required')
      .refine(v => /^\d+(\.\d{0,2})?$/.test(v) && parseFloat(v) > 0, 'Enter a valid positive amount'),
    date: z.string().min(1, 'Date is required'),
    categoryId: z.string().optional(),
    accountId: z.string().min(1, 'Please select an account'),
    toAccountId: z.string().optional(),
    merchant: z.string().optional(),
    notes: z.string().optional(),
    budgetId: z.string().optional(),
  })
  .superRefine((data, ctx) => {
    if (data.type !== 'transfer') {
      if (!data.categoryId)
        ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['categoryId'], message: 'Please select a category' })
      if (!data.merchant?.trim())
        ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['merchant'], message: 'Merchant is required' })
    }
    if (data.type === 'transfer') {
      if (!data.toAccountId)
        ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['toAccountId'], message: 'Please select destination account' })
      else if (data.toAccountId === data.accountId)
        ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['toAccountId'], message: 'Source and destination must differ' })
    }
  })

type FormValues = z.infer<typeof schema>

interface Props {
  categories: Category[]
  accounts: Account[]
  budgets?: ParentBudget[]
  merchants?: string[]
  transaction?: Transaction
  onSuccess: () => void
}

export default function TransactionForm({ categories, accounts, budgets = [], merchants = [], transaction, onSuccess }: Props) {
  const { storage, settings } = useStorage()

  const {
    register,
    handleSubmit,
    control,
    watch,
    setValue,
    formState: { errors, isSubmitting },
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
    defaultValues: {
      type: transaction?.type ?? 'expense',
      amount: transaction ? String(transaction.amount) : '',
      date: transaction?.date ?? getTodayISO(),
      categoryId: transaction?.categoryId ?? '',
      accountId: transaction?.accountId ?? '',
      toAccountId: transaction?.toAccountId ?? '',
      merchant: transaction?.merchant ?? '',
      notes: transaction?.notes ?? '',
      budgetId: transaction?.budgetId ?? '',
    },
  })

  const type = watch('type')
  const accountId = watch('accountId')
  const toAccountId = watch('toAccountId')

  async function onSubmit(data: FormValues) {
    const isTransfer = data.type === 'transfer'
    const payload = {
      type: data.type,
      amount: parseFloat(data.amount),
      date: data.date,
      categoryId: !isTransfer ? (data.categoryId || undefined) : undefined,
      accountId: data.accountId || undefined,
      toAccountId: isTransfer ? (data.toAccountId || undefined) : undefined,
      merchant: !isTransfer ? (data.merchant || undefined) : undefined,
      notes: data.notes || undefined,
      budgetId: data.type === 'expense' ? (data.budgetId || undefined) : undefined,
    }
    if (transaction) {
      await storage.updateTransaction(transaction.id, payload)
    } else {
      await storage.addTransaction(payload)
    }
    onSuccess()
  }

  async function handleDelete() {
    if (!transaction) return
    await storage.deleteTransaction(transaction.id)
    onSuccess()
  }

  const inputCls = 'w-full px-4 py-3 bg-slate-50 dark:bg-slate-800 border-2 border-slate-200 dark:border-slate-700 rounded-xl focus:outline-none focus:border-indigo-500 dark:focus:border-indigo-400 text-slate-900 dark:text-white placeholder:text-slate-400 dark:placeholder:text-slate-600 transition-colors'

  function AccountPillRow({
    label, field, excludeId, error,
  }: {
    label: string
    field: 'accountId' | 'toAccountId'
    excludeId?: string
    error?: string
  }) {
    const current = watch(field)
    return (
      <div>
        <p className="text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">{label}</p>
        <div className="flex gap-2 overflow-x-auto pb-1" role="group" aria-label={label}>
          {accounts.filter(a => a.id !== excludeId).map(acc => {
            const selected = current === acc.id
            return (
              <button
                key={acc.id}
                type="button"
                aria-pressed={selected}
                onClick={() => setValue(field, selected ? '' : acc.id, { shouldValidate: true })}
                className={`flex items-center gap-2 px-3 py-2 rounded-xl text-sm font-medium whitespace-nowrap shrink-0 border-2 transition-colors ${
                  selected
                    ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300'
                    : 'border-transparent bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400'
                }`}
              >
                <span aria-hidden="true">{acc.type === 'credit_card' ? '💳' : '🏦'}</span>
                {acc.name}
              </button>
            )
          })}
        </div>
        {error && <p className="mt-1.5 text-xs text-rose-600 dark:text-rose-400" role="alert">{error}</p>}
      </div>
    )
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-5" noValidate>
      {/* Type toggle */}
      <div className="flex rounded-xl overflow-hidden border-2 border-slate-200 dark:border-slate-700">
        {(['expense', 'income', 'transfer'] as const).map(t => (
          <button
            key={t}
            type="button"
            onClick={() => setValue('type', t, { shouldValidate: true })}
            aria-pressed={type === t}
            className={`flex-1 py-3 text-sm font-semibold transition-colors ${
              type === t
                ? t === 'income'   ? 'bg-emerald-500 text-white'
                : t === 'expense' ? 'bg-rose-500 text-white'
                :                   'bg-indigo-600 text-white'
                : 'text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800'
            }`}
          >
            {t === 'income' ? '↑ Income' : t === 'expense' ? '↓ Expense' : '⇄ Transfer'}
          </button>
        ))}
      </div>

      {/* Amount */}
      <div>
        <label htmlFor="amount" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5">Amount</label>
        <div className="relative">
          <span className="absolute left-4 top-1/2 -translate-y-1/2 text-xl font-semibold text-slate-400 select-none" aria-hidden="true">
            {settings.currencySymbol}
          </span>
          <input
            id="amount"
            type="text"
            inputMode="decimal"
            placeholder="0"
            autoFocus
            autoComplete="off"
            {...register('amount')}
            className="w-full pl-10 pr-4 py-3.5 text-2xl font-bold bg-slate-50 dark:bg-slate-800 border-2 border-slate-200 dark:border-slate-700 rounded-xl focus:outline-none focus:border-indigo-500 dark:focus:border-indigo-400 text-slate-900 dark:text-white placeholder:text-slate-300 dark:placeholder:text-slate-600 transition-colors"
          />
        </div>
        {errors.amount && <p className="mt-1.5 text-xs text-rose-600 dark:text-rose-400" role="alert">{errors.amount.message}</p>}
      </div>

      {/* Date */}
      <div>
        <label htmlFor="txdate" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5">Date</label>
        <input id="txdate" type="date" {...register('date')} className={inputCls} />
        {errors.date && <p className="mt-1.5 text-xs text-rose-600 dark:text-rose-400" role="alert">{errors.date.message}</p>}
      </div>

      {type === 'transfer' ? (
        <>
          <AccountPillRow label="From Account" field="accountId" excludeId={toAccountId} error={errors.accountId?.message} />
          <AccountPillRow label="To Account" field="toAccountId" excludeId={accountId} error={errors.toAccountId?.message} />
        </>
      ) : (
        <>
          <div>
            <p className="text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">Category</p>
            <Controller
              control={control}
              name="categoryId"
              render={({ field }) => (
                <CategoryPicker
                  categories={categories}
                  value={field.value ?? ''}
                  type={type}
                  onChange={field.onChange}
                  error={errors.categoryId?.message}
                />
              )}
            />
          </div>

          {accounts.length > 0 && (
            <AccountPillRow label="Account" field="accountId" error={errors.accountId?.message} />
          )}

          <div>
            <label htmlFor="merchant" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5">Merchant</label>
            <Controller
              control={control}
              name="merchant"
              render={({ field }) => (
                <MerchantInput
                  id="merchant"
                  value={field.value ?? ''}
                  onChange={field.onChange}
                  merchants={merchants}
                  placeholder="e.g. Zomato, Amazon"
                  className={inputCls}
                  error={errors.merchant?.message}
                />
              )}
            />
          </div>

          {/* Optional budget assignment — only for expenses */}
          {type === 'expense' && budgets.length > 0 && (
            <div>
              <p className="text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                Budget <span className="font-normal text-slate-400">(optional)</span>
              </p>
              <Controller
                control={control}
                name="budgetId"
                render={({ field }) => (
                  <div className="flex gap-2 flex-wrap">
                    {budgets.map(b => {
                      const selected = field.value === b.id
                      return (
                        <button
                          key={b.id}
                          type="button"
                          aria-pressed={selected}
                          onClick={() => field.onChange(selected ? '' : b.id)}
                          className={`px-3 py-2 rounded-xl text-sm font-medium border-2 transition-colors ${
                            selected
                              ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300'
                              : 'border-transparent bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400'
                          }`}
                        >
                          🎯 {b.name}
                        </button>
                      )
                    })}
                  </div>
                )}
              />
            </div>
          )}
        </>
      )}

      {/* Notes */}
      <div>
        <label htmlFor="notes" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5">
          Notes <span className="font-normal text-slate-400">(optional)</span>
        </label>
        <textarea
          id="notes"
          rows={2}
          placeholder="Add a note..."
          autoComplete="off"
          autoCorrect="off"
          {...register('notes')}
          className="w-full px-4 py-3 bg-slate-50 dark:bg-slate-800 border-2 border-slate-200 dark:border-slate-700 rounded-xl focus:outline-none focus:border-indigo-500 dark:focus:border-indigo-400 text-slate-900 dark:text-white placeholder:text-slate-400 dark:placeholder:text-slate-600 transition-colors resize-none"
        />
      </div>

      {/* Actions */}
      <div className="flex gap-3 pt-1">
        {transaction && (
          <button
            type="button"
            onClick={handleDelete}
            aria-label="Delete transaction"
            className="flex items-center justify-center w-12 h-12 rounded-xl bg-rose-50 dark:bg-rose-900/20 text-rose-600 dark:text-rose-400 hover:bg-rose-100 dark:hover:bg-rose-900/40 transition-colors shrink-0"
          >
            <svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
              <path d="M3 6h18M19 6l-1 14a2 2 0 01-2 2H8a2 2 0 01-2-2L5 6M10 11v6M14 11v6M9 6V4a1 1 0 011-1h4a1 1 0 011 1v2" />
            </svg>
          </button>
        )}
        <button
          type="submit"
          disabled={isSubmitting}
          className="flex-1 py-3.5 bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 disabled:opacity-60 text-white font-semibold rounded-xl transition-colors min-h-[48px]"
        >
          {isSubmitting ? 'Saving…' : transaction ? 'Save Changes' : 'Add Transaction'}
        </button>
      </div>
    </form>
  )
}
