// Generated by GitHub Copilot
import type { Transaction, Category, Account } from "../../types";
import { formatDate } from "../../utils/date";
import { formatCurrency as fmt } from "../../utils/currency";
import TransactionItem from "./TransactionItem";

interface DayGroup {
  date: string;
  items: Transaction[];
  income: number;
  expense: number;
}

function groupByDay(transactions: Transaction[]): DayGroup[] {
  const map = new Map<string, DayGroup>();
  for (const tx of transactions) {
    if (!map.has(tx.date))
      map.set(tx.date, { date: tx.date, items: [], income: 0, expense: 0 });
    const g = map.get(tx.date)!;
    g.items.push(tx);
    if (tx.type === "income") g.income += tx.amount;
    else if (tx.type === "expense") g.expense += tx.amount;
    // transfers are neutral — excluded from day totals
  }
  return Array.from(map.values()).sort((a, b) => b.date.localeCompare(a.date));
}

interface Props {
  transactions: Transaction[];
  categories: Category[];
  accounts: Account[];
  currencySymbol: string;
  locale: string;
  onEditTransaction: (tx: Transaction) => void;
}

export default function TransactionList({
  transactions,
  categories,
  accounts,
  currencySymbol,
  locale,
  onEditTransaction,
}: Props) {
  const groups = groupByDay(transactions);
  const catMap = new Map(categories.map((c) => [c.id, c]));
  const accMap = new Map(accounts.map((a) => [a.id, a]));
  const fmtAmt = (n: number) => fmt(n, currencySymbol, locale);

  const today = new Date().toISOString().slice(0, 10);
  const yesterday = new Date(Date.now() - 86_400_000)
    .toISOString()
    .slice(0, 10);

  function dayLabel(date: string) {
    if (date === today) return "Today";
    if (date === yesterday) return "Yesterday";
    return formatDate(date, locale);
  }

  if (groups.length === 0) {
    return (
      <div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-8 text-center">
        <span className="text-4xl" aria-hidden="true">
          💸
        </span>
        <p className="mt-3 font-semibold text-slate-700 dark:text-slate-300">
          No transactions yet
        </p>
        <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
          Tap <strong>Add</strong> to record your first income or expense.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {groups.map((group) => (
        <div
          key={group.date}
          className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden"
        >
          <div className="flex items-center justify-between px-4 py-3 border-b border-slate-100 dark:border-slate-800">
            <span className="text-sm font-semibold text-slate-700 dark:text-slate-300">
              {dayLabel(group.date)}
            </span>
            <div className="flex gap-3 text-xs font-medium">
              {group.income > 0 && (
                <span className="text-emerald-600 dark:text-emerald-400">
                  +{fmtAmt(group.income)}
                </span>
              )}
              {group.expense > 0 && (
                <span className="text-slate-500 dark:text-slate-400">
                  -{fmtAmt(group.expense)}
                </span>
              )}
            </div>
          </div>
          <div className="divide-y divide-slate-100 dark:divide-slate-800">
            {group.items.map((tx) => (
              <TransactionItem
                key={tx.id}
                transaction={tx}
                category={tx.categoryId ? catMap.get(tx.categoryId) : undefined}
                toAccount={accMap.get(tx.toAccountId ?? "")}
                currencySymbol={currencySymbol}
                locale={locale}
                onClick={() => onEditTransaction(tx)}
              />
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}
