// Generated by GitHub Copilot
import type { Account } from '../../types'
import { formatCurrency } from '../../utils/currency'
import { useStorage } from '../../hooks/useStorage'

interface Props {
  account: Account
  onEdit: () => void
}

export default function AccountCard({ account, onEdit }: Props) {
  const { settings } = useStorage()
  const isCredit = account.type === 'credit_card'
  const balance = formatCurrency(account.balance, settings.currencySymbol, settings.locale)

  return (
    <button
      type="button"
      onClick={onEdit}
      className="w-full flex items-center gap-4 px-5 py-4 hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors text-left"
    >
      <div
        className="w-10 h-10 rounded-xl flex items-center justify-center text-xl shrink-0"
        style={{ backgroundColor: `${account.color}25` }}
        aria-hidden="true"
      >
        {isCredit ? '💳' : '🏦'}
      </div>
      <div className="flex-1 min-w-0">
        <p className="text-sm font-medium text-slate-900 dark:text-white">{account.name}</p>
        <p className="text-xs text-slate-500 dark:text-slate-400">{isCredit ? 'Credit Card' : 'Savings'}</p>
      </div>
      <div className="text-right shrink-0">
        <p className={`text-sm font-semibold ${isCredit ? 'text-rose-600 dark:text-rose-400' : 'text-slate-900 dark:text-white'}`}>
          {isCredit ? '-' : ''}{balance}
        </p>
        {isCredit && <p className="text-xs text-slate-400 dark:text-slate-500">owed</p>}
      </div>
    </button>
  )
}
