// Generated by GitHub Copilot
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import type { Account } from '../../types'
import { useStorage } from '../../hooks/useStorage'
import { ACCOUNT_COLORS } from '../../utils/accountColors'

const schema = z.object({
  name: z.string().min(1, 'Name is required').max(50),
  type: z.enum(['savings', 'credit_card']),
  balance: z
    .string()
    .min(1, 'Balance is required')
    .refine(v => !isNaN(parseFloat(v)), 'Enter a valid amount'),
  color: z.string().min(1),
})

type FormValues = z.infer<typeof schema>

interface Props {
  account?: Account
  onSuccess: () => void
}

export default function AccountForm({ account, onSuccess }: Props) {
  const { storage } = useStorage()
  const {
    register,
    handleSubmit,
    watch,
    setValue,
    formState: { errors, isSubmitting },
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
    defaultValues: {
      name: account?.name ?? '',
      type: account?.type ?? 'savings',
      balance: account !== undefined ? String(account.balance) : '0',
      color: account?.color ?? ACCOUNT_COLORS[0],
    },
  })

  const type = watch('type')
  const color = watch('color')

  async function onSubmit(data: FormValues) {
    const payload = {
      name: data.name.trim(),
      type: data.type,
      balance: parseFloat(data.balance),
      color: data.color,
    }
    if (account) {
      await storage.updateAccount(account.id, payload)
    } else {
      await storage.addAccount(payload)
    }
    onSuccess()
  }

  async function handleDelete() {
    if (!account) return
    await storage.deleteAccount(account.id)
    onSuccess()
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-5" noValidate>
      {/* Name */}
      <div>
        <label htmlFor="accname" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5">
          Account Name
        </label>
        <input
          id="accname"
          type="text"
          placeholder="e.g. SBI Salary, HDFC Spending"
          autoFocus
          autoComplete="off"
          autoCorrect="off"
          {...register('name')}
          className="w-full px-4 py-3 bg-slate-50 dark:bg-slate-800 border-2 border-slate-200 dark:border-slate-700 rounded-xl focus:outline-none focus:border-indigo-500 dark:focus:border-indigo-400 text-slate-900 dark:text-white placeholder:text-slate-400 dark:placeholder:text-slate-600 transition-colors"
        />
        {errors.name && <p className="mt-1.5 text-xs text-rose-600 dark:text-rose-400" role="alert">{errors.name.message}</p>}
      </div>

      {/* Type */}
      <div>
        <p className="text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">Account Type</p>
        <div className="flex rounded-xl overflow-hidden border-2 border-slate-200 dark:border-slate-700">
          {(['savings', 'credit_card'] as const).map(t => (
            <button
              key={t}
              type="button"
              onClick={() => setValue('type', t, { shouldValidate: true })}
              aria-pressed={type === t}
              className={`flex-1 flex items-center justify-center gap-2 py-3 text-sm font-semibold transition-colors ${
                type === t
                  ? 'bg-indigo-600 text-white'
                  : 'text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800'
              }`}
            >
              <span aria-hidden="true">{t === 'credit_card' ? '💳' : '🏦'}</span>
              {t === 'credit_card' ? 'Credit Card' : 'Savings'}
            </button>
          ))}
        </div>
      </div>

      {/* Balance */}
      <div>
        <label htmlFor="accbalance" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5">
          {type === 'credit_card' ? 'Amount Currently Owed' : 'Current Balance'}
        </label>
        <div className="relative">
          <span className="absolute left-4 top-1/2 -translate-y-1/2 text-xl font-semibold text-slate-400 select-none" aria-hidden="true">₹</span>
          <input
            id="accbalance"
            type="text"
            inputMode="decimal"
            placeholder="0"
            {...register('balance')}
            className="w-full pl-10 pr-4 py-3.5 text-2xl font-bold bg-slate-50 dark:bg-slate-800 border-2 border-slate-200 dark:border-slate-700 rounded-xl focus:outline-none focus:border-indigo-500 dark:focus:border-indigo-400 text-slate-900 dark:text-white placeholder:text-slate-300 dark:placeholder:text-slate-600 transition-colors"
          />
        </div>
        {errors.balance && <p className="mt-1.5 text-xs text-rose-600 dark:text-rose-400" role="alert">{errors.balance.message}</p>}
        {type === 'credit_card' && (
          <p className="mt-1.5 text-xs text-slate-500 dark:text-slate-400">Enter how much you currently owe on this card.</p>
        )}
      </div>

      {/* Color */}
      <div>
        <p className="text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">Color</p>
        <div className="flex gap-2.5 flex-wrap" role="radiogroup" aria-label="Account color">
          {ACCOUNT_COLORS.map(c => (
            <button
              key={c}
              type="button"
              role="radio"
              aria-checked={color === c}
              aria-label={`Color ${c}`}
              onClick={() => setValue('color', c)}
              className={`w-9 h-9 rounded-full transition-transform ${
                color === c ? 'scale-125 ring-2 ring-offset-2 ring-slate-400 dark:ring-slate-500' : 'hover:scale-110'
              }`}
              style={{ backgroundColor: c }}
            />
          ))}
        </div>
      </div>

      {/* Actions */}
      <div className="flex gap-3 pt-1">
        {account && (
          <button
            type="button"
            onClick={handleDelete}
            aria-label="Delete account"
            className="flex items-center justify-center w-12 h-12 rounded-xl bg-rose-50 dark:bg-rose-900/20 text-rose-600 dark:text-rose-400 hover:bg-rose-100 dark:hover:bg-rose-900/40 transition-colors shrink-0"
          >
            <svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
              <path d="M3 6h18M19 6l-1 14a2 2 0 01-2 2H8a2 2 0 01-2-2L5 6M10 11v6M14 11v6M9 6V4a1 1 0 011-1h4a1 1 0 011 1v2" />
            </svg>
          </button>
        )}
        <button
          type="submit"
          disabled={isSubmitting}
          className="flex-1 py-3.5 bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 disabled:opacity-60 text-white font-semibold rounded-xl transition-colors min-h-[48px]"
        >
          {isSubmitting ? 'Saving…' : account ? 'Save Changes' : 'Add Account'}
        </button>
      </div>
    </form>
  )
}
