// Generated by GitHub Copilot
import { useState, useRef, useId } from 'react'

interface Props {
  id: string
  value: string
  onChange: (value: string) => void
  /** Merchants pre-sorted by frequency (most used first). */
  merchants: string[]
  placeholder?: string
  className?: string
  error?: string
}

const MAX_SUGGESTIONS = 8

/**
 * Controlled text input with an inline dropdown of previously used merchant names.
 * Filters by case-insensitive substring as the user types.
 */
export default function MerchantInput({ id, value, onChange, merchants, placeholder, className, error }: Props) {
  const [open, setOpen] = useState(false)
  const [highlighted, setHighlighted] = useState(-1)
  const inputRef = useRef<HTMLInputElement>(null)
  const listId = useId()

  const suggestions = value.trim()
    ? merchants
        .filter(m => m.toLowerCase().includes(value.toLowerCase()))
        .slice(0, MAX_SUGGESTIONS)
    : merchants.slice(0, MAX_SUGGESTIONS)

  function pick(merchant: string) {
    onChange(merchant)
    setOpen(false)
    setHighlighted(-1)
    inputRef.current?.focus()
  }

  function handleKeyDown(e: React.KeyboardEvent<HTMLInputElement>) {
    if (!open || suggestions.length === 0) return
    if (e.key === 'ArrowDown') {
      e.preventDefault()
      setHighlighted(i => Math.min(i + 1, suggestions.length - 1))
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      setHighlighted(i => Math.max(i - 1, 0))
    } else if (e.key === 'Enter' && highlighted >= 0) {
      e.preventDefault()
      pick(suggestions[highlighted])
    } else if (e.key === 'Escape') {
      setOpen(false)
      setHighlighted(-1)
    }
  }

  return (
    <div className="relative">
      <input
        ref={inputRef}
        id={id}
        type="text"
        role="combobox"
        aria-autocomplete="list"
        aria-expanded={open && suggestions.length > 0}
        aria-controls={listId}
        aria-activedescendant={highlighted >= 0 ? `${listId}-opt-${highlighted}` : undefined}
        value={value}
        placeholder={placeholder}
        autoComplete="off"
        onChange={e => {
          onChange(e.target.value)
          setOpen(true)
          setHighlighted(-1)
        }}
        onFocus={() => setOpen(true)}
        onBlur={() => setTimeout(() => setOpen(false), 150)}
        onKeyDown={handleKeyDown}
        className={className}
      />
      {open && suggestions.length > 0 && (
        <ul
          id={listId}
          role="listbox"
          className="absolute z-20 left-0 right-0 mt-1 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl shadow-lg overflow-hidden max-h-56 overflow-y-auto"
        >
          {suggestions.map((m, i) => (
            <li
              key={m}
              id={`${listId}-opt-${i}`}
              role="option"
              aria-selected={i === highlighted}
              onMouseDown={() => pick(m)}
              onMouseEnter={() => setHighlighted(i)}
              className={`px-4 py-2.5 text-sm cursor-pointer transition-colors ${
                i === highlighted
                  ? 'bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300'
                  : 'text-slate-800 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-700'
              }`}
            >
              {m}
            </li>
          ))}
        </ul>
      )}
      {error && <p className="mt-1.5 text-xs text-rose-600 dark:text-rose-400" role="alert">{error}</p>}
    </div>
  )
}
